ARG FRAPPE_IMAGE=frappe/erpnext
ARG FRAPPE_TAG=v15.92.3
FROM ${FRAPPE_IMAGE}:${FRAPPE_TAG}

USER root
RUN apt-get update \
    && apt-get install -y --no-install-recommends nodejs npm \
    && rm -rf /var/lib/apt/lists/*
USER frappe

ENV PYTHONPATH=/home/frappe/frappe-bench/apps:/home/frappe/frappe-bench/apps/frappe:/home/frappe/frappe-bench/apps/erpnext:/home/frappe/frappe-bench/apps/master_plan_it
