@extends('layouts.app')

@section('content')
<x-common.page-breadcrumb pageTitle="Dashboard" />
@if ($error)<div class="mb-6 rounded-xl border border-error-200 bg-error-50 p-4 text-sm text-error-700">{{ $error }}</div>@endif
<div class="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
 <div><p class="text-sm text-gray-500 dark:text-gray-400">Panoramica economica del periodo selezionato.</p></div>
 @if ($yearOptions !== [])<form method="GET"><label class="mb-1 block text-xs font-medium text-gray-500" for="year">Anno di pianificazione</label><select id="year" name="year" onchange="this.form.submit()" class="h-10 min-w-44 rounded-lg border border-gray-300 bg-white px-3 text-sm text-gray-700 dark:border-gray-700 dark:bg-gray-800 dark:text-gray-300">@foreach($yearOptions as $year)<option value="{{ $year['value'] }}" @selected($selectedYear === $year['value'])>{{ $year['label'] }}{{ $year['active'] ? '' : ' · inattivo' }}</option>@endforeach</select></form>@endif
</div>
@if (!$selectedYear)
 <div class="rounded-2xl border border-gray-200 bg-white p-8 text-center dark:border-gray-800 dark:bg-white/[0.03]"><h3 class="font-semibold text-gray-800 dark:text-white">Nessun anno di pianificazione</h3><p class="mt-2 text-sm text-gray-500">Non è disponibile un anno selezionabile per il contesto corrente.</p></div>
@else
 @php($summary = $summary ?? [])
 <div class="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">
  @foreach ([['Posizione attuale', $summary['officialCurrentPosition'] ?? '—', 'wallet'], ['Consuntivo confermato', $summary['actualConfirmed'] ?? '—', 'receipt'], ['Da confermare', $summary['actualToConfirm'] ?? '—', 'document'], ['Plafond residuo', $summary['plafondResidual'] ?? '—', 'chart']] as [$label, $value, $icon])
   <div class="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-white/[0.03] md:p-6"><div class="flex h-12 w-12 items-center justify-center rounded-xl bg-gray-100 text-gray-800 dark:bg-gray-800 dark:text-white"><x-ui.icon :name="$icon" /></div><div class="mt-5"><p class="text-sm text-gray-500 dark:text-gray-400">{{ $label }}</p><h3 class="mt-2 text-xl font-bold text-gray-800 dark:text-white/90">{{ $value }}</h3></div></div>
  @endforeach
 </div>
 <div class="mt-6 grid grid-cols-12 gap-6">
  <section class="col-span-12 rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-white/[0.03] xl:col-span-8 sm:p-6"><div class="mb-6 flex items-start justify-between gap-4"><div><h3 class="text-lg font-semibold text-gray-800 dark:text-white/90">Andamento mensile</h3><p class="mt-1 text-sm text-gray-500 dark:text-gray-400">Posizione economica nel periodo selezionato.</p></div><span class="rounded-lg bg-gray-100 px-3 py-2 text-xs font-medium text-gray-600 dark:bg-gray-800 dark:text-gray-300">Base {{ $summary['officialBasis'] ?? '—' }}</span></div><div id="dashboard-monthly-chart" class="h-72" data-chart='@json($charts['monthly'] ?? ['labels' => [], 'datasets' => []])'></div></section>
  <section class="col-span-12 rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-white/[0.03] xl:col-span-4 sm:p-6"><h3 class="text-lg font-semibold text-gray-800 dark:text-white/90">Per tipologia</h3><p class="mt-1 text-sm text-gray-500 dark:text-gray-400">Ripartizione delle voci.</p><div id="dashboard-type-chart" class="mt-4 h-64" data-chart='@json($charts['byType'] ?? ['labels' => [], 'datasets' => []])'></div></section>
  <section class="col-span-12 rounded-2xl border border-gray-200 bg-white dark:border-gray-800 dark:bg-white/[0.03] xl:col-span-7"><div class="flex items-center justify-between border-b border-gray-100 px-5 py-5 dark:border-gray-800 sm:px-6"><div><h3 class="font-semibold text-gray-800 dark:text-white/90">Spese aggiornate di recente</h3><p class="mt-1 text-sm text-gray-500">Ultime modifiche nel periodo.</p></div><a class="text-sm font-medium text-brand-500 hover:text-brand-600" href="{{ route('operational.expenses.index') }}">Vedi tutte</a></div><div class="divide-y divide-gray-100 dark:divide-gray-800">@forelse($recentExpenses as $expense)<a class="flex items-center justify-between gap-4 px-5 py-4 hover:bg-gray-50 dark:hover:bg-white/[0.02] sm:px-6" href="{{ $expense['href'] }}"><span class="min-w-0"><span class="block truncate text-sm font-medium text-gray-800 dark:text-white">{{ $expense['label'] }}</span><span class="mt-1 block text-xs text-gray-500">{{ $expense['date'] }}</span></span><svg class="h-4 w-4 shrink-0 text-gray-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m9 18 6-6-6-6"/></svg></a>@empty<div class="px-5 py-8 text-sm text-gray-500 sm:px-6">Nessuna spesa per questo anno.</div>@endforelse</div></section>
  <section class="col-span-12 rounded-2xl border border-gray-200 bg-white dark:border-gray-800 dark:bg-white/[0.03] xl:col-span-5"><div class="border-b border-gray-100 px-5 py-5 dark:border-gray-800 sm:px-6"><h3 class="font-semibold text-gray-800 dark:text-white/90">Eventi contrattuali</h3><p class="mt-1 text-sm text-gray-500">Rinnovi e scadenze entro un anno.</p></div><div class="divide-y divide-gray-100 dark:divide-gray-800">@forelse($upcomingContractEvents as $event)<a class="flex items-center justify-between gap-3 px-5 py-4 hover:bg-gray-50 dark:hover:bg-white/[0.02] sm:px-6" href="{{ $event['href'] }}"><span class="min-w-0"><span class="block truncate text-sm font-medium text-gray-800 dark:text-white">{{ $event['label'] }}</span><span class="mt-1 block text-xs text-gray-500">{{ $event['secondary'] }} · {{ $event['date'] }}</span></span></a>@empty<div class="px-5 py-8 text-sm text-gray-500 sm:px-6">Nessun evento contrattuale imminente.</div>@endforelse</div></section>
 </div>
 @if (!$hasEconomicData)<div class="mt-6 rounded-xl border border-warning-200 bg-warning-50 p-4 text-sm text-warning-700">L'anno selezionato non contiene ancora dati economici.</div>@endif
@endif
@endsection
