import type { ExpenseRow } from "../../api/expenses";
import { formatDate } from "../../presentation/formatters";
import { domainLabel } from "../../presentation/labels";
import Badge from "../ui/badge/Badge";
import { Table, TableBody, TableCell, TableHeader, TableRow } from "../ui/table";
import ExpenseMoney from "./ExpenseMoney";

export default function ExpenseRowsTable({ rows }: { rows: ExpenseRow[] }) {
  if (rows.length === 0) return <p className="rounded-xl border border-dashed border-gray-300 p-6 text-sm text-gray-500">Questa spesa non contiene righe correnti.</p>;
  return <div className="max-w-full overflow-x-auto rounded-xl border border-gray-200 dark:border-white/[0.05]"><Table><TableHeader className="border-b border-gray-100 dark:border-white/[0.05]"><TableRow>{["Tipo", "Descrizione", "Fornitore", "Pianificazione", "Data", "Netto", "IVA", "Lordo"].map((heading) => <TableCell key={heading} isHeader className="whitespace-nowrap px-5 py-3 text-start text-theme-xs font-medium text-gray-500">{heading}</TableCell>)}</TableRow></TableHeader><TableBody className="divide-y divide-gray-100 dark:divide-white/[0.05]">{rows.map((row) => <TableRow key={row.id}><TableCell className="px-5 py-4 text-sm font-medium">{domainLabel(row.type)}{row.generated ? <span className="block text-xs font-normal text-gray-500">Generata da contratto</span> : null}</TableCell><TableCell className="min-w-56 px-5 py-4 text-sm">{row.description}{row.is_extra ? <span className="block text-xs text-gray-500">Extra</span> : null}</TableCell><TableCell className="px-5 py-4 text-sm">{row.vendor_name ?? "—"}</TableCell><TableCell className="px-5 py-4">{row.is_current_planning ? <Badge color="success">Corrente</Badge> : row.type === "actual" ? <Badge color="info">Actual</Badge> : <span className="text-sm text-gray-500">Alternativa</span>}</TableCell><TableCell className="px-5 py-4 text-sm">{row.spend_date ? formatDate(row.spend_date) : "—"}</TableCell><TableCell className="px-5 py-4 text-sm"><ExpenseMoney money={row.totals} component="net" /></TableCell><TableCell className="px-5 py-4 text-sm"><ExpenseMoney money={row.totals} component="vat" /></TableCell><TableCell className="px-5 py-4 text-sm font-medium"><ExpenseMoney money={row.totals} component="gross" /></TableCell></TableRow>)}</TableBody></Table></div>;
}
