const domainLabels = {
  estimate: "Stima",
  quote: "Preventivo",
  actual: "Consuntivo",
  ordinary: "Ordinaria",
  plafond: "Plafond",
  active: "Attivo",
  inactive: "Inattivo",
  monthly: "Mensile",
  annual: "Annuale",
  confirmed: "Confermato",
  to_confirm: "Da confermare",
  all: "Tutto il periodo",
  start: "Mese iniziale",
  end: "Mese finale",
  pending: "In attesa",
  generated: "Generata",
  suppressed: "Soppressa",
  create: "Creazione",
  update: "Modifica",
  deactivate: "Disattivazione",
  reactivate: "Riattivazione",
  restore: "Ripristino",
  delete: "Eliminazione",
  renewal: "Rinnovo",
  contract_end: "Scadenza contratto",
  net: "Netto",
  gross: "Lordo",
  idea: "Idea",
  proposed: "Proposto",
  approved: "Approvato",
  deferred: "Rinviato",
  rejected: "Respinto",
  primary: "Primary",
  excluded: "Escluso",
  potential: "Potential",
} as const;

export type DomainLabelKey = keyof typeof domainLabels;

export function domainLabel(value: string | null | undefined): string {
  if (!value) return "—";
  return domainLabels[value.toLowerCase() as DomainLabelKey] ?? value;
}

const systemRoles: Record<string, string> = {
  Administrator: "Amministratore di Piattaforma",
  "Platform Administrator": "Amministratore di Piattaforma",
  Editor: "Operatore",
  Viewer: "Lettore",
};

export function roleLabel(name: string): string {
  return systemRoles[name] ?? name;
}

export const abilityLabels: Record<string, string> = {
  "platform.tenants.view": "Visualizzare i Tenant",
  "platform.tenants.create": "Creare Tenant",
  "platform.tenants.update": "Modificare Tenant",
  "platform.tenants.deactivate": "Disattivare Tenant",
  "platform.tenants.reactivate": "Riattivare Tenant",
  "platform.users.manage": "Gestire gli utenti di piattaforma",
  "platform.roles.manage": "Gestire i ruoli di piattaforma",
  "platform.settings.manage": "Gestire le impostazioni di piattaforma",
  "deletion-reason-setting.manage": "Gestire le motivazioni di eliminazione",
  "platform.audit.view-global": "Visualizzare l'audit globale",
  "platform.migration.run": "Eseguire migrazioni",
  "platform.portability.import": "Importare dati di portabilità",
  "platform.backup.run": "Eseguire backup",
  "platform.restore.run": "Eseguire ripristini",
  "platform.deploy.view": "Visualizzare le distribuzioni",
  "dashboard.view": "Visualizzare la Panoramica",
  "audit.view": "Visualizzare l'audit",
  "notification.view": "Visualizzare le notifiche",
  "tenant-settings.view": "Visualizzare le impostazioni generali del Tenant",
  "tenant-settings.update": "Modificare le impostazioni generali del Tenant",
  "planning-year.view": "Visualizzare gli anni di pianificazione",
  "planning-year.create": "Creare anni di pianificazione",
  "planning-year.deactivate": "Disattivare anni di pianificazione",
  "planning-year.update": "Chiudere Budget annuali",
  "planning-year.reactivate": "Riattivare anni di pianificazione",
  "cost-center.view": "Visualizzare i centri di costo",
  "cost-center.create": "Creare centri di costo",
  "cost-center.update": "Modificare centri di costo",
  "cost-center.delete": "Eliminare centri di costo",
  "cost-center.deactivate": "Disattivare centri di costo",
  "cost-center.reactivate": "Riattivare centri di costo",
  "cost-center.view-revisions": "Visualizzare lo storico dei centri di costo",
  "cost-center.restore-revision": "Ripristinare revisioni dei centri di costo",
  "vendor.view": "Visualizzare i fornitori",
  "vendor.create": "Creare fornitori",
  "vendor.update": "Modificare fornitori",
  "vendor.delete": "Eliminare fornitori",
  "vendor.deactivate": "Disattivare fornitori",
  "vendor.reactivate": "Riattivare fornitori",
  "vendor.view-revisions": "Visualizzare lo storico dei fornitori",
  "vendor.restore-revision": "Ripristinare revisioni dei fornitori",
  "expense.view": "Visualizzare le spese",
  "expense.create": "Creare spese",
  "expense.update": "Modificare spese",
  "expense.delete": "Eliminare spese",
  "expense.view-revisions": "Visualizzare lo storico delle spese",
  "expense.restore-revision": "Ripristinare revisioni delle spese",
  "expense.print": "Stampare spese",
  "expense.export": "Esportare spese",
  "attachment.view": "Visualizzare allegati",
  "attachment.upload": "Caricare allegati",
  "attachment.delete": "Eliminare allegati",
  "project.view": "Visualizzare progetti",
  "project.create": "Creare progetti",
  "project.update": "Modificare progetti",
  "project.delete": "Eliminare progetti",
  "project.view-revisions": "Visualizzare lo storico dei progetti",
  "project.restore-revision": "Ripristinare revisioni dei progetti",
  "contract.view": "Visualizzare i contratti",
  "contract.create": "Creare contratti",
  "contract.update": "Modificare contratti",
  "contract.delete": "Eliminare contratti",
  "contract.view-revisions": "Visualizzare lo storico dei contratti",
  "contract.restore-revision": "Ripristinare revisioni dei contratti",
  "contract.generate-occurrence": "Generare ricorrenze contrattuali",
  "contract.suppress-generation": "Sopprimere generazioni contrattuali",
  "contract.resume-generation": "Riprendere generazioni contrattuali",
  "contract.view-generation-history": "Visualizzare lo storico delle generazioni",
  "budget.view": "Visualizzare il Budget",
  "budget.select-reference": "Selezionare il Budget di riferimento",
  "report.view": "Visualizzare i Report",
  "report.print": "Stampare Report",
  "report.export-filtered": "Esportare Report filtrati",
  "report.export-complete": "Esportare Report completi",
  "budget-version.view": "Visualizzare le versioni Budget",
  "budget-version.create": "Creare versioni Budget",
  "budget-version.update-draft": "Modificare bozze Budget",
  "budget-version.publish": "Pubblicare versioni Budget",
  "budget-version.compare": "Confrontare versioni Budget",
  "budget-version.select-reference": "Selezionare versioni Budget di riferimento",
  "scenario.view": "Visualizzare scenari",
  "scenario.create": "Creare scenari",
  "scenario.update": "Modificare scenari",
  "scenario.archive": "Archiviare scenari",
  "scenario.delete": "Eliminare scenari",
  "scenario.compare": "Confrontare scenari",
  "tenant-portability.export": "Esportare dati del Tenant",
};

export function abilityLabel(ability: string): string {
  return abilityLabels[ability] ?? ability;
}

export const abilityGroupLabels: Record<string, string> = {
  platform: "Piattaforma",
  dashboard: "Panoramica",
  audit: "Audit",
  notification: "Notifiche",
  "tenant-settings": "Impostazioni generali del Tenant",
  "planning-year": "Anni di pianificazione",
  "cost-center": "Centri di costo",
  vendor: "Fornitori",
  expense: "Spese",
  attachment: "Allegati",
  project: "Progetti",
  contract: "Contratti",
  budget: "Budget",
  report: "Report",
  "budget-version": "Versioni Budget",
  scenario: "Scenari",
  "tenant-portability": "Portabilità Tenant",
  "deletion-reason-setting": "Motivazioni di eliminazione",
};

export function abilityGroup(ability: string): string {
  const key = ability.split(".")[0] ?? ability;
  return abilityGroupLabels[key] ?? key;
}
