import { useCallback, useEffect, useState } from "react";
import { ApiError } from "../../api/client";
import { createVendor, deactivateVendor, deleteVendor, listVendorHistory, listVendors, reactivateVendor, restoreVendor, updateVendor, type Revision, type Vendor } from "../../api/vendors";
import { CheckCircleIcon, CloseLineIcon, PencilIcon, TimeIcon, TrashBinIcon } from "../../icons";
import { formatDateTime } from "../../presentation/formatters";
import { domainLabel } from "../../presentation/labels";
import ComponentCard from "../common/ComponentCard";
import IconButton from "../common/IconButton";
import PageBreadcrumb from "../common/PageBreadCrumb";
import InputField from "../form/input/InputField";
import Label from "../form/Label";
import Alert from "../ui/alert/Alert";
import Badge from "../ui/badge/Badge";
import Button from "../ui/button/Button";
import { Modal } from "../ui/modal";
import { Table, TableBody, TableCell, TableHeader, TableRow } from "../ui/table";

export default function VendorsView({ canView, canCreate, canUpdate, canDeactivate, canReactivate, canDelete, canHistory, canRestore }: { canView: boolean; canCreate: boolean; canUpdate: boolean; canDeactivate: boolean; canReactivate: boolean; canDelete: boolean; canHistory: boolean; canRestore: boolean }) {
  const [vendors,setVendors]=useState<Vendor[]>([]); const [editing,setEditing]=useState<Vendor|null>(null); const [formOpen,setFormOpen]=useState(false); const [form,setForm]=useState({name:"",vat_number:"",email:"",phone:"",address:""}); const [history,setHistory]=useState<{vendor:Vendor;rows:Revision[]}|null>(null); const [deleteTarget,setDeleteTarget]=useState<Vendor|null>(null); const [error,setError]=useState<string|null>(null); const [loading,setLoading]=useState(false); const [busy,setBusy]=useState(false);
  const load=useCallback(async()=>{if(!canView)return;setLoading(true);try{setVendors((await listVendors({per_page:100})).data);setError(null);}catch(requestError){setError(ApiError.from(requestError).message);}finally{setLoading(false);}},[canView]);
  useEffect(()=>{void load();},[load]);
  const openForm=(vendor:Vendor|null)=>{setEditing(vendor);setForm(vendor?{name:vendor.name,vat_number:vendor.vat_number??"",email:vendor.email??"",phone:vendor.phone??"",address:vendor.address??""}:{name:"",vat_number:"",email:"",phone:"",address:""});setFormOpen(true);};
  const submit=async(event:React.FormEvent)=>{event.preventDefault();setBusy(true);setError(null);try{const saved=editing?await updateVendor(editing.id,{...form,lock_version:editing.lock_version}):await createVendor(form);setVendors(rows=>editing?rows.map(row=>row.id===saved.id?saved:row):[saved,...rows]);setFormOpen(false);setEditing(null);}catch(requestError){setError(ApiError.from(requestError).message);}finally{setBusy(false);}};
  const changeState=async(vendor:Vendor,active:boolean)=>{setBusy(true);try{const saved=active?await reactivateVendor(vendor.id,vendor.lock_version):await deactivateVendor(vendor.id,vendor.lock_version);setVendors(rows=>rows.map(row=>row.id===saved.id?saved:row));}catch(requestError){setError(ApiError.from(requestError).message);}finally{setBusy(false);}};
  const showHistory=async(vendor:Vendor)=>{setBusy(true);try{setHistory({vendor,rows:(await listVendorHistory(vendor.id,{per_page:100})).data});}catch(requestError){setError(ApiError.from(requestError).message);}finally{setBusy(false);}};
  const restore=async(revision:Revision)=>{if(!history||revision.source_revision_id===null)return;setBusy(true);try{const saved=await restoreVendor(history.vendor.id,revision.source_revision_id,history.vendor.lock_version);setVendors(rows=>rows.map(row=>row.id===saved.id?saved:row));setHistory(null);}catch(requestError){setError(ApiError.from(requestError).message);}finally{setBusy(false);}};
  const remove=async()=>{if(!deleteTarget)return;setBusy(true);try{await deleteVendor(deleteTarget.id,deleteTarget.lock_version);setVendors(rows=>rows.filter(row=>row.id!==deleteTarget.id));setDeleteTarget(null);}catch(requestError){setError(ApiError.from(requestError).message);}finally{setBusy(false);}};
  return <><PageBreadcrumb pageTitle="Fornitori" subtitle="Anagrafica dei fornitori del Tenant corrente." actions={canCreate?<Button size="sm" onClick={()=>openForm(null)}>Nuovo Fornitore</Button>:null}/>{error?<Alert variant="error" title="Operazione non riuscita" message={error}/>:null}<ComponentCard title="Registro Fornitori">{loading?<Alert variant="info" title="Caricamento dei fornitori" message="Recupero del registro in corso."/>:vendors.length===0?<Alert variant="info" title="Nessun fornitore" message="Non sono presenti fornitori nel Tenant corrente."/>:<div className="max-w-full overflow-x-auto"><Table><TableHeader className="border-y border-gray-100 dark:border-gray-800"><TableRow>{["Nome","Contatti","Partita IVA","Stato","Azioni"].map(head=><TableCell key={head} isHeader className="py-3 text-start text-theme-xs font-medium text-gray-500 dark:text-gray-400">{head}</TableCell>)}</TableRow></TableHeader><TableBody className="divide-y divide-gray-100 dark:divide-gray-800">{vendors.map(vendor=><TableRow key={vendor.id}><TableCell className="py-3 font-medium text-gray-800 dark:text-white/90">{vendor.name}</TableCell><TableCell className="py-3 text-sm text-gray-600 dark:text-gray-300"><span className="block">{vendor.email??"—"}</span>{vendor.phone?<span className="text-xs text-gray-500 dark:text-gray-400">{vendor.phone}</span>:null}</TableCell><TableCell className="py-3 text-sm text-gray-600 dark:text-gray-300">{vendor.vat_number??"—"}</TableCell><TableCell className="py-3"><Badge color={vendor.active?"success":"light"}>{vendor.active?"Attivo":"Inattivo"}</Badge></TableCell><TableCell className="py-3"><div className="flex items-center gap-2">{canUpdate?<IconButton icon={PencilIcon} label={`Modifica ${vendor.name}`} onClick={()=>openForm(vendor)} disabled={busy}/>:null}{vendor.active&&canDeactivate?<IconButton icon={CloseLineIcon} label={`Disattiva ${vendor.name}`} onClick={()=>void changeState(vendor,false)} disabled={busy}/>:null}{!vendor.active&&canReactivate?<IconButton icon={CheckCircleIcon} label={`Riattiva ${vendor.name}`} onClick={()=>void changeState(vendor,true)} disabled={busy}/>:null}{canHistory?<IconButton icon={TimeIcon} label={`Storico di ${vendor.name}`} onClick={()=>void showHistory(vendor)} disabled={busy}/>:null}{canDelete?<IconButton icon={TrashBinIcon} label={`Elimina ${vendor.name}`} onClick={()=>setDeleteTarget(vendor)} disabled={busy} destructive/>:null}</div></TableCell></TableRow>)}</TableBody></Table></div>}</ComponentCard>
  <Modal isOpen={formOpen} onClose={()=>setFormOpen(false)} className="max-w-2xl p-6"><h2 className="pr-12 text-lg font-semibold text-gray-800 dark:text-white/90">{editing?"Modifica Fornitore":"Nuovo Fornitore"}</h2><form onSubmit={submit} className="mt-5 grid gap-4 md:grid-cols-2"><div><Label htmlFor="vendor-name">Nome</Label><InputField id="vendor-name" value={form.name} onChange={event=>setForm({...form,name:event.target.value})}/></div><div><Label htmlFor="vendor-vat">Partita IVA</Label><InputField id="vendor-vat" value={form.vat_number} onChange={event=>setForm({...form,vat_number:event.target.value})}/></div><div><Label htmlFor="vendor-email">Email</Label><InputField id="vendor-email" type="email" value={form.email} onChange={event=>setForm({...form,email:event.target.value})}/></div><div><Label htmlFor="vendor-phone">Telefono</Label><InputField id="vendor-phone" value={form.phone} onChange={event=>setForm({...form,phone:event.target.value})}/></div><div className="md:col-span-2"><Label htmlFor="vendor-address">Indirizzo</Label><InputField id="vendor-address" value={form.address} onChange={event=>setForm({...form,address:event.target.value})}/></div><div className="flex justify-end gap-3 md:col-span-2"><Button type="button" variant="outline" onClick={()=>setFormOpen(false)}>Annulla</Button><Button disabled={busy}>{busy?"Salvataggio…":editing?"Salva Modifiche":"Crea Fornitore"}</Button></div></form></Modal>
  <Modal isOpen={history!==null} onClose={()=>setHistory(null)} className="max-w-2xl p-6"><h2 className="pr-12 text-lg font-semibold text-gray-800 dark:text-white/90">Storico Revisioni</h2><div className="mt-5 divide-y divide-gray-100 dark:divide-gray-800">{history?.rows.length?history.rows.map((revision,index)=><div key={`${revision.source_revision_id??index}`} className="flex items-center justify-between gap-3 py-3"><div><p className="text-sm font-medium text-gray-800 dark:text-white/90">{domainLabel(revision.operation)}</p><p className="text-xs text-gray-500 dark:text-gray-400">{formatDateTime(revision.timestamp)} · {revision.actor??"—"}</p></div>{canRestore&&revision.source_revision_id!==null?<Button size="sm" variant="outline" onClick={()=>void restore(revision)} disabled={busy}>Ripristina</Button>:null}</div>):<p className="text-sm text-gray-500 dark:text-gray-400">Nessuna revisione disponibile.</p>}</div></Modal>
  <Modal isOpen={deleteTarget!==null} onClose={()=>setDeleteTarget(null)} className="max-w-lg p-6"><h2 className="pr-12 text-lg font-semibold text-gray-800 dark:text-white/90">Eliminare il fornitore?</h2><p className="mt-2 text-sm text-gray-500 dark:text-gray-400">Il fornitore verrà rimosso dal registro se non è vincolato da dati correnti o storici.</p><div className="mt-6 flex justify-end gap-3"><Button variant="outline" onClick={()=>setDeleteTarget(null)}>Annulla</Button><Button onClick={()=>void remove()} disabled={busy}>{busy?"Eliminazione…":"Elimina Fornitore"}</Button></div></Modal></>;
}
