import { useCallback, useEffect, useState } from "react";
import { ApiError } from "../../api/client";
import { createCostCenter, deactivateCostCenter, deleteCostCenter, listCostCenterHistory, listCostCenters, reactivateCostCenter, restoreCostCenter, updateCostCenter, type CostCenter, type Revision } from "../../api/costCenters";
import { BoxCubeIcon, CheckCircleIcon, CloseLineIcon, PencilIcon, TimeIcon, TrashBinIcon } from "../../icons";
import { formatDateTime } from "../../presentation/formatters";
import { domainLabel } from "../../presentation/labels";
import ComponentCard from "../common/ComponentCard";
import IconButton from "../common/IconButton";
import PageBreadcrumb from "../common/PageBreadCrumb";
import InputField from "../form/input/InputField";
import Label from "../form/Label";
import Select from "../form/Select";
import Alert from "../ui/alert/Alert";
import Badge from "../ui/badge/Badge";
import Button from "../ui/button/Button";
import { Modal } from "../ui/modal";
import { Table, TableBody, TableCell, TableHeader, TableRow } from "../ui/table";

function flatten(items:CostCenter[],depth=0):CostCenter[]{return items.flatMap(item=>[{...item,depth},...flatten(item.children??[],depth+1)]);}

export default function CostCentersView({ canView, canCreate, canUpdate, canDeactivate, canReactivate, canDelete, canHistory, canRestore }: { canView:boolean;canCreate:boolean;canUpdate:boolean;canDeactivate:boolean;canReactivate:boolean;canDelete:boolean;canHistory:boolean;canRestore:boolean }) {
  const [tree,setTree]=useState<CostCenter[]>([]); const [selected,setSelected]=useState<CostCenter|null>(null); const [form,setForm]=useState({name:"",parent_id:""}); const [formOpen,setFormOpen]=useState(false); const [history,setHistory]=useState<{item:CostCenter;rows:Revision[]}|null>(null); const [deleteTarget,setDeleteTarget]=useState<CostCenter|null>(null); const [error,setError]=useState<string|null>(null); const [loading,setLoading]=useState(false); const [busy,setBusy]=useState(false); const rows=flatten(tree);
  const load=useCallback(async()=>{if(!canView)return;setLoading(true);try{setTree((await listCostCenters({per_page:100})).data);setError(null);}catch(requestError){setError(ApiError.from(requestError).message);}finally{setLoading(false);}},[canView]); useEffect(()=>{void load();},[load]);
  const begin=(item:CostCenter|null)=>{setSelected(item);setForm({name:item?.name??"",parent_id:item?.parent_id?String(item.parent_id):""});setFormOpen(true);};
  const submit=async(event:React.FormEvent)=>{event.preventDefault();setBusy(true);try{const input={name:form.name.trim(),parent_id:form.parent_id?Number.parseInt(form.parent_id,10):null};if(selected)await updateCostCenter(selected.id,{...input,lock_version:selected.lock_version});else await createCostCenter(input);await load();setFormOpen(false);}catch(requestError){setError(ApiError.from(requestError).message);}finally{setBusy(false);}};
  const change=async(item:CostCenter,active:boolean)=>{setBusy(true);try{if(active)await reactivateCostCenter(item.id,item.lock_version);else await deactivateCostCenter(item.id,item.lock_version);await load();}catch(requestError){setError(ApiError.from(requestError).message);}finally{setBusy(false);}};
  const showHistory=async(item:CostCenter)=>{setBusy(true);try{setHistory({item,rows:(await listCostCenterHistory(item.id,{per_page:100})).data});}catch(requestError){setError(ApiError.from(requestError).message);}finally{setBusy(false);}};
  const restore=async(revision:Revision)=>{if(!history||revision.source_revision_id===null)return;setBusy(true);try{await restoreCostCenter(history.item.id,revision.source_revision_id,history.item.lock_version);await load();setHistory(null);}catch(requestError){setError(ApiError.from(requestError).message);}finally{setBusy(false);}};
  const remove=async()=>{if(!deleteTarget)return;setBusy(true);try{await deleteCostCenter(deleteTarget.id,deleteTarget.lock_version);await load();setDeleteTarget(null);}catch(requestError){setError(ApiError.from(requestError).message);}finally{setBusy(false);}};
  return <><PageBreadcrumb pageTitle="Centri di Costo" subtitle="Gerarchia dei centri di costo del Tenant corrente." actions={canCreate?<Button size="sm" onClick={()=>begin(null)}>Nuovo Centro di Costo</Button>:null}/>{error?<Alert variant="error" title="Operazione non riuscita" message={error}/>:null}<ComponentCard title="Gerarchia dei Centri di Costo">{loading?<Alert variant="info" title="Caricamento dei centri di costo" message="Recupero della gerarchia in corso."/>:rows.length===0?<Alert variant="info" title="Nessun centro di costo" message="Non sono presenti centri di costo nel Tenant corrente."/>:<div className="max-w-full overflow-x-auto"><Table><TableHeader className="border-y border-gray-100 dark:border-gray-800"><TableRow>{["Nome","Centro superiore","Stato","Azioni"].map(head=><TableCell key={head} isHeader className="py-3 text-start text-theme-xs font-medium text-gray-500 dark:text-gray-400">{head}</TableCell>)}</TableRow></TableHeader><TableBody className="divide-y divide-gray-100 dark:divide-gray-800">{rows.map(item=><TableRow key={item.id}><TableCell className="py-3"><div className="flex items-center gap-2" style={{paddingLeft:`${(item.depth??0)*20}px`}}>{Array.from({length:item.depth??0},(_,index)=><span key={index} className="h-px w-3 bg-gray-300 dark:bg-gray-700" aria-hidden="true"/>)}<BoxCubeIcon className="h-5 w-5 text-gray-500 dark:text-gray-400"/><span className="font-medium text-gray-800 dark:text-white/90">{item.name}</span></div></TableCell><TableCell className="py-3 text-sm text-gray-600 dark:text-gray-300">{rows.find(parent=>parent.id===item.parent_id)?.name??"—"}</TableCell><TableCell className="py-3"><Badge color={item.active?"success":"light"}>{item.active?"Attivo":"Inattivo"}</Badge></TableCell><TableCell className="py-3"><div className="flex items-center gap-2">{canUpdate?<IconButton icon={PencilIcon} label={`Modifica ${item.name}`} onClick={()=>begin(item)} disabled={busy}/>:null}{item.active&&canDeactivate?<IconButton icon={CloseLineIcon} label={`Disattiva ${item.name}`} onClick={()=>void change(item,false)} disabled={busy}/>:null}{!item.active&&canReactivate?<IconButton icon={CheckCircleIcon} label={`Riattiva ${item.name}`} onClick={()=>void change(item,true)} disabled={busy}/>:null}{canHistory?<IconButton icon={TimeIcon} label={`Storico di ${item.name}`} onClick={()=>void showHistory(item)} disabled={busy}/>:null}{canDelete?<IconButton icon={TrashBinIcon} label={`Elimina ${item.name}`} onClick={()=>setDeleteTarget(item)} disabled={busy} destructive/>:null}</div></TableCell></TableRow>)}</TableBody></Table></div>}</ComponentCard>
  <Modal isOpen={formOpen} onClose={()=>setFormOpen(false)} className="max-w-xl p-6"><h2 className="pr-12 text-lg font-semibold text-gray-800 dark:text-white/90">{selected?"Modifica Centro di Costo":"Nuovo Centro di Costo"}</h2><form onSubmit={submit} className="mt-5 space-y-4"><div><Label htmlFor="cc-name">Nome</Label><InputField id="cc-name" value={form.name} onChange={event=>setForm({...form,name:event.target.value})}/></div><div><Label htmlFor="cc-parent">Centro superiore</Label><Select id="cc-parent" options={rows.filter(item=>item.id!==selected?.id).map(item=>({value:String(item.id),label:`${"› ".repeat(item.depth??0)}${item.name}`}))} value={form.parent_id} placeholder="Nessun centro superiore" allowEmpty onChange={parent_id=>setForm({...form,parent_id})}/></div><div className="flex justify-end gap-3"><Button type="button" variant="outline" onClick={()=>setFormOpen(false)}>Annulla</Button><Button disabled={busy}>{busy?"Salvataggio…":selected?"Salva Modifiche":"Crea Centro"}</Button></div></form></Modal>
  <Modal isOpen={history!==null} onClose={()=>setHistory(null)} className="max-w-2xl p-6"><h2 className="pr-12 text-lg font-semibold text-gray-800 dark:text-white/90">Storico Revisioni</h2><div className="mt-5 divide-y divide-gray-100 dark:divide-gray-800">{history?.rows.length?history.rows.map((revision,index)=><div key={`${revision.source_revision_id??index}`} className="flex items-center justify-between gap-3 py-3"><div><p className="text-sm font-medium text-gray-800 dark:text-white/90">{domainLabel(revision.operation)}</p><p className="text-xs text-gray-500 dark:text-gray-400">{formatDateTime(revision.timestamp)} · {revision.actor??"—"}</p></div>{canRestore&&revision.source_revision_id!==null?<Button size="sm" variant="outline" onClick={()=>void restore(revision)} disabled={busy}>Ripristina</Button>:null}</div>):<p className="text-sm text-gray-500 dark:text-gray-400">Nessuna revisione disponibile.</p>}</div></Modal>
  <Modal isOpen={deleteTarget!==null} onClose={()=>setDeleteTarget(null)} className="max-w-lg p-6"><h2 className="pr-12 text-lg font-semibold text-gray-800 dark:text-white/90">Eliminare il centro di costo?</h2><p className="mt-2 text-sm text-gray-500 dark:text-gray-400">L'operazione è disponibile solo se la gerarchia e i riferimenti storici lo consentono.</p><div className="mt-6 flex justify-end gap-3"><Button variant="outline" onClick={()=>setDeleteTarget(null)}>Annulla</Button><Button onClick={()=>void remove()} disabled={busy}>{busy?"Eliminazione…":"Elimina Centro"}</Button></div></Modal></>;
}
