@extends('layouts.app')
@section('title', $expense['title'])
@section('content')
<div class="mb-6 flex flex-wrap items-start justify-between gap-4"><div><a class="text-sm text-brand-500" href="{{ route('operational.expenses.index') }}">Spese</a><h1 class="mt-1 text-2xl font-semibold text-gray-800 dark:text-white">{{ $expense['title'] }}</h1><p class="mt-1 text-sm text-gray-500">Dettaglio e risultati monetari correnti.</p></div>
@if($abilities['update'] || $abilities['delete'])
    <x-common.dropdown-menu label="Azioni" icon="receipt">
        @if($abilities['update'])<a class="flex items-center gap-2 rounded-lg px-3 py-2 text-sm hover:bg-gray-100 dark:hover:bg-white/5" href="{{ route('operational.expenses.edit',$expense['id']) }}"><x-ui.icon name="document" />Modifica spesa</a>@endif
        @if($abilities['delete'])<button @click="$dispatch('open-delete-expense')" class="mt-1 flex w-full items-center gap-2 border-t border-gray-100 px-3 py-2 text-left text-sm text-error-500 dark:border-gray-800"><x-ui.icon name="receipt" />Elimina spesa</button>@endif
    </x-common.dropdown-menu>
@endif</div>
<div class="grid gap-5 lg:grid-cols-3"><section class="rounded-2xl border border-gray-200 bg-white p-5 lg:col-span-2 dark:border-gray-800 dark:bg-white/[0.03]"><dl class="grid gap-5 sm:grid-cols-2"><div><dt class="text-xs font-medium uppercase text-gray-500">Anno</dt><dd class="mt-1 text-sm text-gray-800 dark:text-white">{{ $expense['planningYearLabel'] }}</dd></div><div><dt class="text-xs font-medium uppercase text-gray-500">Centro di costo</dt><dd class="mt-1 text-sm text-gray-800 dark:text-white">{{ $expense['costCenterName'] }}</dd></div><div><dt class="text-xs font-medium uppercase text-gray-500">Tipo</dt><dd class="mt-1 text-sm capitalize text-gray-800 dark:text-white">{{ $expense['kind'] }}</dd></div>@if($expense['contractId'])<div><dt class="text-xs font-medium uppercase text-gray-500">Contratto</dt><dd class="mt-1 text-sm">@if($expense['contractIsCurrent'])<a class="text-brand-500" href="{{ $expense['contractHref'] }}">{{ $expense['contractTitle'] }}</a>@else{{ $expense['contractTitle'] }} <span class="text-xs text-gray-500">Fonte preservata</span>@endif</dd></div>@endif @if($expense['notes'])<div class="sm:col-span-2"><dt class="text-xs font-medium uppercase text-gray-500">Note</dt><dd class="mt-1 whitespace-pre-wrap text-sm text-gray-800 dark:text-white">{{ $expense['notes'] }}</dd></div>@endif</dl></section><section class="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-white/[0.03]"><dl class="space-y-4">@foreach(['Netto'=>'net','IVA'=>'vat','Lordo'=>'gross'] as $label=>$field)<div><dt class="text-xs font-medium uppercase text-gray-500">{{ $label }}</dt><dd class="mt-1 font-semibold text-gray-800 dark:text-white">{{ $expense[$field] }}</dd></div>@endforeach</dl></section></div>
<h2 class="mb-3 mt-6 text-lg font-semibold text-gray-800 dark:text-white">Righe spesa</h2><div class="grid gap-4">@forelse($expense['rows'] as $row)<article class="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-white/[0.03]"><div class="flex flex-wrap items-start justify-between gap-4"><div><div class="flex gap-2"><span class="rounded-full bg-gray-100 px-2.5 py-1 text-xs capitalize text-gray-600 dark:bg-white/10 dark:text-gray-300">{{ $row['type'] }}</span>@if($row['confirmationState'])<span class="rounded-full px-2.5 py-1 text-xs {{ $row['confirmationState']==='confirmed' ? 'bg-success-50 text-success-600' : 'bg-warning-50 text-warning-600' }}">{{ $row['confirmationState']==='confirmed' ? 'Confermato' : 'Da confermare' }}</span>@endif @if($row['isSystemManaged'])<span class="rounded-full bg-brand-50 px-2.5 py-1 text-xs text-brand-500">Gestita da contratto</span>@endif</div><h3 class="mt-3 font-medium text-gray-800 dark:text-white">{{ $row['description'] }}</h3><p class="mt-1 text-sm text-gray-500">{{ $row['vendorName'] ?? 'Nessun fornitore' }}@if($row['externalReference']) · Rif. {{ $row['externalReference'] }}@endif</p></div>@if($row['canConfirm'] && $abilities['confirmActual'])<form method="POST" action="{{ route('operational.expenses.rows.confirm',[$expense['id'],$row['id']]) }}">@csrf<input type="hidden" name="lock_version" value="{{ $row['lockVersion'] }}"><button class="rounded-lg border border-gray-300 px-4 py-2 text-sm dark:border-gray-700">Conferma actual</button></form>@endif</div><dl class="mt-5 grid gap-4 border-t border-gray-100 pt-4 text-sm sm:grid-cols-3 lg:grid-cols-6 dark:border-gray-800">@foreach(['Netto'=>'net','IVA'=>'vat','Lordo'=>'gross','Data'=>'spendDate','Distribuzione'=>'distribution','Riferimento'=>'externalReference'] as $label=>$key)<div><dt class="text-xs text-gray-500">{{ $label }}</dt><dd class="mt-1 text-gray-800 dark:text-white">{{ $row[$key] ?? '—' }}</dd></div>@endforeach</dl></article>@empty<div class="rounded-2xl border border-dashed border-gray-300 p-8 text-center text-sm text-gray-500">Nessuna riga corrente.</div>@endforelse</div>
@if($abilities['delete'])<div x-data="{open:false, generated: {{ collect($expense['rows'])->contains(fn($r)=>$r['sourceKey'] !== null) ? 'true':'false' }} }" @open-delete-expense.window="open=true"><div x-cloak x-show="open" class="fixed inset-0 z-50 flex items-center justify-center p-5"><div @click="open=false" class="absolute inset-0 bg-gray-900/50"></div><form method="POST" action="{{ route('operational.expenses.destroy',$expense['id']) }}" class="relative w-full max-w-lg rounded-2xl bg-white p-6 dark:bg-gray-900">@csrf @method('DELETE')<h2 class="text-lg font-semibold">Elimina spesa</h2><p class="mt-2 text-sm text-gray-500">L'operazione rimuove la spesa dai registri correnti. Le evidenze di revisione restano conservate.</p><input type="hidden" name="lock_version" value="{{ $expense['lockVersion'] }}"><template x-if="generated"><div class="mt-4"><label class="mb-1 block text-sm font-medium">Consentire nuova generazione dell'occorrenza?</label><select name="allow_regeneration" class="h-11 w-full rounded-lg border border-gray-300 px-3"><option value="">Scegli un'opzione</option><option value="1">Sì, consenti</option><option value="0">No, sopprimi</option></select></div></template><div class="mt-6 flex justify-end gap-3"><button type="button" @click="open=false" class="rounded-lg px-4 py-2 text-sm">Annulla</button><button class="rounded-lg bg-error-500 px-4 py-2 text-sm text-white">Elimina</button></div></form></div></div>@endif
@endsection
