@extends('layouts.app')

@section('content')
    <x-common.page-breadcrumb pageTitle="Report economico" />
    <p class="-mt-4 mb-6 text-sm text-gray-500 dark:text-gray-400">Righe economiche correnti in sola lettura e posizione calcolata dal server.</p>
    <form method="GET" action="{{ route('operational.reports.index') }}" class="mb-6 grid gap-4 rounded-2xl border border-gray-200 bg-white p-5 sm:grid-cols-[minmax(0,1fr)_minmax(0,1fr)_auto] dark:border-gray-800 dark:bg-white/[0.03]">
        <div><label for="year" class="mb-1.5 block text-sm font-medium text-gray-700 dark:text-gray-400">Anno di pianificazione</label><select id="year" name="year" class="h-11 w-full rounded-lg border border-gray-300 bg-transparent px-4 py-2.5 text-sm text-gray-800 outline-hidden focus:border-brand-300 focus:ring-3 focus:ring-brand-500/10 dark:border-gray-700 dark:bg-gray-900 dark:text-white/90"><option value="">Seleziona un anno</option>@foreach($yearOptions as $year)<option value="{{ $year['value'] }}" @selected($selectedYear === $year['value'])>{{ $year['label'] }}{{ $year['active'] ? ' · Attivo' : '' }}</option>@endforeach</select></div>
        <div><label for="cost_center" class="mb-1.5 block text-sm font-medium text-gray-700 dark:text-gray-400">Centro di costo</label><select id="cost_center" name="cost_center" class="h-11 w-full rounded-lg border border-gray-300 bg-transparent px-4 py-2.5 text-sm text-gray-800 outline-hidden focus:border-brand-300 focus:ring-3 focus:ring-brand-500/10 dark:border-gray-700 dark:bg-gray-900 dark:text-white/90"><option value="">Tutti i centri di costo</option>@foreach($costCenterOptions as $costCenter)<option value="{{ $costCenter['value'] }}" @selected($selectedCostCenter === $costCenter['value'])>{{ $costCenter['label'] }}</option>@endforeach</select></div>
        <x-ui.button type="submit" variant="outline" class="self-end">Aggiorna</x-ui.button>
    </form>
    @if(!count($yearOptions))
        <div class="rounded-2xl border border-dashed border-gray-300 bg-white px-6 py-14 text-center dark:border-gray-700 dark:bg-white/[0.03]"><h2 class="text-base font-medium text-gray-800 dark:text-white/90">Nessun anno disponibile</h2><p class="mt-2 text-sm text-gray-500 dark:text-gray-400">Crea un anno di pianificazione prima di consultare il report.</p></div>
    @elseif($summary)
        @php($metrics = [['Posizione corrente ufficiale', 'officialCurrentPosition', strtoupper($summary['officialBasis']).' basis'], ['Netto', 'net', null], ['IVA', 'vat', null], ['Lordo', 'gross', null], ['Preventivo', 'estimate', null], ['Offerta', 'quote', null], ['Consuntivo', 'actual', null], ['Consuntivo da confermare', 'actualToConfirm', null], ['Consuntivo confermato', 'actualConfirmed', null], ['Extra', 'extra', null], ['Plafond assegnato', 'plafondAllocated', null], ['Plafond utilizzato', 'plafondConsumed', null], ['Plafond residuo', 'plafondResidual', null], ['Superamento plafond', 'plafondOverrun', null]])
        <section aria-labelledby="report-summary" class="mb-6"><div class="mb-3 flex items-center justify-between gap-4"><h1 id="report-summary" class="text-lg font-semibold text-gray-800 dark:text-white/90">Posizione economica</h1>@if(!$hasEconomicData)<span class="text-xs text-gray-500 dark:text-gray-400">I valori sono pari a zero per questo risultato vuoto.</span>@endif</div><div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">@foreach($metrics as $index => [$label, $key, $detail])<article @class(['rounded-2xl border p-5', 'border-brand-200 bg-brand-50 dark:border-brand-500/30 dark:bg-brand-500/10' => $index === 0, 'border-gray-200 bg-white dark:border-gray-800 dark:bg-white/[0.03]' => $index !== 0])><p class="text-sm font-medium text-gray-500 dark:text-gray-400">{{ $label }}</p><p class="mt-2 text-xl font-bold text-gray-800 dark:text-white/90">{{ $summary[$key] }}</p>@if(isset($detail))<p class="mt-1 text-xs font-semibold text-brand-600 dark:text-brand-400">{{ $detail }}</p>@endif</article>@endforeach</div></section>
        @if($hasEconomicData)
            <section class="overflow-hidden rounded-2xl border border-gray-200 bg-white dark:border-gray-800 dark:bg-white/[0.03]"><div class="flex flex-col gap-2 border-b border-gray-100 px-6 py-5 sm:flex-row sm:items-center sm:justify-between dark:border-gray-800"><div><h2 class="text-base font-medium text-gray-800 dark:text-white/90">Righe di spesa correnti</h2><p class="mt-1 text-sm text-gray-500 dark:text-gray-400">Ordinate per identificativo riga, per un risultato stabile in sola lettura.</p></div><p class="text-sm text-gray-500 dark:text-gray-400">{{ $lines['from'] }}–{{ $lines['to'] }} di {{ $lines['total'] }}</p></div><div class="overflow-x-auto"><table class="min-w-full"><thead class="border-b border-gray-100 dark:border-gray-800"><tr>@foreach(['Riga','Centro di costo','Componente','Conferma','Netto','IVA','Lordo'] as $header)<th @class(['px-5 py-3 text-xs font-medium text-gray-500 dark:text-gray-400', 'text-right' => in_array($header, ['Netto','IVA','Lordo']), 'text-left' => !in_array($header, ['Netto','IVA','Lordo'])])>{{ $header }}</th>@endforeach</tr></thead><tbody class="divide-y divide-gray-100 dark:divide-gray-800">@foreach($lines['data'] as $line)<tr><td class="px-5 py-4 text-sm text-gray-500 dark:text-gray-400">#{{ $line['id'] }}</td><td class="px-5 py-4 text-sm text-gray-500 dark:text-gray-400">{{ $line['costCenterName'] }}</td><td class="px-5 py-4 text-sm capitalize text-gray-500 dark:text-gray-400">{{ $line['type'] }}</td><td class="px-5 py-4 text-sm text-gray-500 dark:text-gray-400">{{ $line['confirmationState'] ? str_replace('_', ' ', $line['confirmationState']) : '—' }}</td><td class="px-5 py-4 text-right text-sm font-semibold text-gray-800 dark:text-white/90">{{ $line['net'] }}</td><td class="px-5 py-4 text-right text-sm text-gray-500 dark:text-gray-400">{{ $line['vat'] }}</td><td class="px-5 py-4 text-right text-sm text-gray-500 dark:text-gray-400">{{ $line['gross'] }}</td></tr>@endforeach</tbody></table></div><div class="flex items-center justify-between border-t border-gray-100 px-6 py-4 dark:border-gray-800"><span class="text-sm text-gray-500 dark:text-gray-400">Pagina {{ $lines['currentPage'] }} di {{ $lines['lastPage'] }}</span><nav class="flex gap-1" aria-label="Paginazione">
                @foreach($lines['links'] as $link)
                    @if($link['url'])
                        <a href="{{ $link['url'] }}" class="rounded-lg px-3 py-2 text-sm hover:bg-gray-100 dark:hover:bg-white/[0.05]">{{ $link['label'] }}</a>
                    @else
                        <span @class(['rounded-lg px-3 py-2 text-sm', 'bg-brand-50 text-brand-600 dark:bg-brand-500/15 dark:text-brand-400' => $link['active'], 'text-gray-400' => !$link['active']])>{{ $link['label'] }}</span>
                    @endif
                @endforeach
            </nav></div></section>
        @else
            <div class="rounded-2xl border border-dashed border-gray-300 bg-white px-6 py-14 text-center dark:border-gray-700 dark:bg-white/[0.03]"><h2 class="text-base font-medium text-gray-800 dark:text-white/90">Nessun dato economico corrente</h2><p class="mt-2 text-sm text-gray-500 dark:text-gray-400">Nessuna riga di spesa corrente e non eliminata corrisponde ai filtri selezionati.</p></div>
        @endif
    @endif
@endsection
