import { useCallback, useEffect, useMemo, useState } from "react";
import { ApiError } from "../../api/client";
import { createRole, deleteRole, listAbilities, listRoles, updateRole, type Ability, type Role } from "../../api/roles";
import { PencilIcon, TrashBinIcon } from "../../icons";
import { abilityGroup, abilityLabel, roleLabel } from "../../presentation/labels";
import ComponentCard from "../common/ComponentCard";
import IconButton from "../common/IconButton";
import PageBreadcrumb from "../common/PageBreadCrumb";
import Label from "../form/Label";
import Checkbox from "../form/input/Checkbox";
import InputField from "../form/input/InputField";
import Alert from "../ui/alert/Alert";
import Badge from "../ui/badge/Badge";
import Button from "../ui/button/Button";
import { Modal } from "../ui/modal";
import { Table, TableBody, TableCell, TableHeader, TableRow } from "../ui/table";

export default function RolesView({canManage}:{canManage:boolean}){
  const [roles,setRoles]=useState<Role[]>([]); const [abilities,setAbilities]=useState<Ability[]>([]); const [selected,setSelected]=useState<Role|null>(null); const [name,setName]=useState(""); const [selectedAbilities,setSelectedAbilities]=useState<string[]>([]); const [formOpen,setFormOpen]=useState(false); const [deleteTarget,setDeleteTarget]=useState<Role|null>(null); const [error,setError]=useState<string|null>(null); const [loading,setLoading]=useState(false); const [busy,setBusy]=useState(false);
  const load=useCallback(async()=>{if(!canManage)return;setLoading(true);try{const [roleResult,abilityResult]=await Promise.all([listRoles(),listAbilities()]);setRoles(roleResult.data);setAbilities(abilityResult.data);}catch(requestError){setError(ApiError.from(requestError).message);}finally{setLoading(false);}},[canManage]);useEffect(()=>{void load();},[load]);
  const grouped=useMemo(()=>abilities.reduce<Record<string,Ability[]>>((result,ability)=>{const group=abilityGroup(ability.name);(result[group]??=[]).push(ability);return result;},{}),[abilities]);
  const begin=(role:Role|null)=>{setSelected(role);setName(role?.name??"");setSelectedAbilities(role?.abilities??[]);setFormOpen(true);};
  const submit=async(event:React.FormEvent)=>{event.preventDefault();setBusy(true);try{const saved=selected?await updateRole(selected.id,name.trim(),selectedAbilities):await createRole(name.trim(),selectedAbilities);setRoles(items=>selected?items.map(item=>item.id===saved.id?saved:item):[...items,saved]);setFormOpen(false);}catch(requestError){setError(ApiError.from(requestError).message);}finally{setBusy(false);}};
  const remove=async()=>{if(!deleteTarget)return;setBusy(true);try{await deleteRole(deleteTarget.id);setRoles(items=>items.filter(item=>item.id!==deleteTarget.id));setDeleteTarget(null);}catch(requestError){setError(ApiError.from(requestError).message);}finally{setBusy(false);}};
  return <><PageBreadcrumb pageTitle="Ruoli" subtitle="Ruoli e autorizzazioni del Tenant corrente." actions={<Button size="sm" onClick={()=>begin(null)}>Nuovo Ruolo</Button>}/>{error?<Alert variant="error" title="Operazione non riuscita" message={error}/>:null}<ComponentCard title="Registro Ruoli">{loading?<Alert variant="info" title="Caricamento dei ruoli" message="Recupero del registro in corso."/>:roles.length===0?<Alert variant="info" title="Nessun ruolo" message="Non sono presenti ruoli nel Tenant corrente."/>:<div className="max-w-full overflow-x-auto"><Table><TableHeader className="border-y border-gray-100 dark:border-gray-800"><TableRow>{["Ruolo","Autorizzazioni","Azioni"].map(head=><TableCell key={head} isHeader className="py-3 text-start text-theme-xs font-medium text-gray-500 dark:text-gray-400">{head}</TableCell>)}</TableRow></TableHeader><TableBody className="divide-y divide-gray-100 dark:divide-gray-800">{roles.map(role=><TableRow key={role.id}><TableCell className="py-3 font-medium text-gray-800 dark:text-white/90">{roleLabel(role.name)}</TableCell><TableCell className="py-3"><Badge color="info" size="sm">{role.abilities.length} {role.abilities.length===1?"autorizzazione":"autorizzazioni"}</Badge></TableCell><TableCell className="py-3"><div className="flex items-center gap-2"><IconButton icon={PencilIcon} label={`Modifica ${roleLabel(role.name)}`} onClick={()=>begin(role)} disabled={busy}/><IconButton icon={TrashBinIcon} label={`Elimina ${roleLabel(role.name)}`} onClick={()=>setDeleteTarget(role)} disabled={busy} destructive/></div></TableCell></TableRow>)}</TableBody></Table></div>}</ComponentCard>
  <Modal isOpen={formOpen} onClose={()=>setFormOpen(false)} className="max-h-[90vh] max-w-4xl overflow-y-auto p-6"><h2 className="pr-12 text-lg font-semibold text-gray-800 dark:text-white/90">{selected?"Modifica Ruolo":"Nuovo Ruolo"}</h2><form onSubmit={submit} className="mt-5 space-y-5"><div><Label htmlFor="role-name">Nome</Label><InputField id="role-name" value={name} onChange={event=>setName(event.target.value)}/></div><fieldset><legend className="mb-3 text-sm font-medium text-gray-700 dark:text-gray-300">Autorizzazioni</legend><div className="grid grid-cols-1 gap-4 lg:grid-cols-2">{Object.entries(grouped).map(([group,items])=><section key={group} className="rounded-xl border border-gray-200 p-4 dark:border-gray-800"><h3 className="mb-3 font-medium text-gray-800 dark:text-white/90">{group}</h3><div className="space-y-3">{items.map(ability=><Checkbox key={ability.name} id={`ability-${ability.name}`} label={abilityLabel(ability.name)} checked={selectedAbilities.includes(ability.name)} onChange={checked=>setSelectedAbilities(current=>checked?[...current,ability.name]:current.filter(item=>item!==ability.name))}/>)}</div></section>)}</div></fieldset><div className="flex justify-end gap-3"><Button type="button" variant="outline" onClick={()=>setFormOpen(false)}>Annulla</Button><Button disabled={busy}>{busy?"Salvataggio…":selected?"Salva Modifiche":"Crea Ruolo"}</Button></div></form></Modal>
  <Modal isOpen={deleteTarget!==null} onClose={()=>setDeleteTarget(null)} className="max-w-lg p-6"><h2 className="pr-12 text-lg font-semibold text-gray-800 dark:text-white/90">Eliminare il ruolo?</h2><p className="mt-2 text-sm text-gray-500 dark:text-gray-400">Il ruolo può essere eliminato soltanto se ogni utente interessato conserva almeno un altro ruolo.</p><div className="mt-6 flex justify-end gap-3"><Button variant="outline" onClick={()=>setDeleteTarget(null)}>Annulla</Button><Button onClick={()=>void remove()} disabled={busy}>{busy?"Eliminazione…":"Elimina Ruolo"}</Button></div></Modal></>;
}
