@extends('layouts.app')

@section('content')
    <x-common.page-breadcrumb pageTitle="Budget corrente" />
    <p class="-mt-4 mb-6 text-sm text-gray-500 dark:text-gray-400">Posizione corrente dell'anno, calcolata dalle righe di spesa attive.</p>

    <form method="GET" action="{{ route('operational.budget.index') }}" class="mb-6 grid gap-4 rounded-2xl border border-gray-200 bg-white p-5 sm:grid-cols-[minmax(0,1fr)_minmax(0,1fr)_auto] dark:border-gray-800 dark:bg-white/[0.03]">
        <div><label for="year" class="mb-1.5 block text-sm font-medium text-gray-700 dark:text-gray-400">Anno di pianificazione</label><select id="year" name="year" class="h-11 w-full rounded-lg border border-gray-300 bg-transparent px-4 py-2.5 text-sm text-gray-800 outline-hidden focus:border-brand-300 focus:ring-3 focus:ring-brand-500/10 dark:border-gray-700 dark:bg-gray-900 dark:text-white/90"><option value="">Seleziona un anno</option>@foreach($yearOptions as $year)<option value="{{ $year['value'] }}" @selected($selectedYear === $year['value'])>{{ $year['label'] }}{{ $year['active'] ? ' · Attivo' : '' }}</option>@endforeach</select></div>
        <div><label for="cost_center" class="mb-1.5 block text-sm font-medium text-gray-700 dark:text-gray-400">Centro di costo</label><select id="cost_center" name="cost_center" class="h-11 w-full rounded-lg border border-gray-300 bg-transparent px-4 py-2.5 text-sm text-gray-800 outline-hidden focus:border-brand-300 focus:ring-3 focus:ring-brand-500/10 dark:border-gray-700 dark:bg-gray-900 dark:text-white/90"><option value="">Tutti i centri di costo</option>@foreach($costCenterOptions as $costCenter)<option value="{{ $costCenter['value'] }}" @selected($selectedCostCenter === $costCenter['value'])>{{ $costCenter['label'] }}</option>@endforeach</select></div>
        <x-ui.button type="submit" variant="outline" class="self-end">Aggiorna</x-ui.button>
    </form>

    @if(!count($yearOptions))
        <div class="rounded-2xl border border-dashed border-gray-300 bg-white px-6 py-14 text-center dark:border-gray-700 dark:bg-white/[0.03]"><h2 class="text-base font-medium text-gray-800 dark:text-white/90">Nessun anno disponibile</h2><p class="mt-2 text-sm text-gray-500 dark:text-gray-400">Crea un anno di pianificazione prima di registrare attività economiche.</p></div>
    @elseif($summary)
        @php($metrics = [['Posizione corrente ufficiale', 'officialCurrentPosition', strtoupper($summary['officialBasis']).' basis'], ['Netto', 'net', null], ['IVA', 'vat', null], ['Lordo', 'gross', null], ['Preventivo', 'estimate', null], ['Offerta', 'quote', null], ['Consuntivo', 'actual', null], ['Consuntivo da confermare', 'actualToConfirm', null], ['Consuntivo confermato', 'actualConfirmed', null], ['Extra', 'extra', null], ['Plafond assegnato', 'plafondAllocated', null], ['Plafond utilizzato', 'plafondConsumed', null], ['Plafond residuo', 'plafondResidual', null], ['Superamento plafond', 'plafondOverrun', null]])
        <section aria-labelledby="budget-summary"><div class="mb-3 flex items-center justify-between gap-4"><h1 id="budget-summary" class="text-lg font-semibold text-gray-800 dark:text-white/90">Posizione economica</h1>@if(!$hasEconomicData)<span class="text-xs text-gray-500 dark:text-gray-400">I valori sono pari a zero per questo risultato vuoto.</span>@endif</div><div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">@foreach($metrics as $index => [$label, $key, $detail])<article @class(['rounded-2xl border p-5', 'border-brand-200 bg-brand-50 dark:border-brand-500/30 dark:bg-brand-500/10' => $index === 0, 'border-gray-200 bg-white dark:border-gray-800 dark:bg-white/[0.03]' => $index !== 0])><p class="text-sm font-medium text-gray-500 dark:text-gray-400">{{ $label }}</p><p class="mt-2 text-xl font-bold text-gray-800 dark:text-white/90">{{ $summary[$key] }}</p>@if(isset($detail))<p class="mt-1 text-xs font-semibold text-brand-600 dark:text-brand-400">{{ $detail }}</p>@endif</article>@endforeach</div></section>

        @if($hasEconomicData)
            <section class="mt-6 grid gap-6 xl:grid-cols-2">
                <article class="rounded-2xl border border-gray-200 bg-white dark:border-gray-800 dark:bg-white/[0.03]"><div class="border-b border-gray-100 px-6 py-5 dark:border-gray-800"><h2 class="text-base font-medium text-gray-800 dark:text-white/90">Componenti</h2><p class="mt-1 text-sm text-gray-500 dark:text-gray-400">Valori correnti calcolati dal server.</p></div><div id="budget-components-chart" class="min-h-72 p-6" data-chart="{{ json_encode($chart, JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT) }}" aria-label="Grafico componenti del budget"></div><p class="sr-only">La tabella a fianco espone gli stessi valori del grafico.</p></article>
                <article class="overflow-hidden rounded-2xl border border-gray-200 bg-white dark:border-gray-800 dark:bg-white/[0.03]"><div class="border-b border-gray-100 px-6 py-5 dark:border-gray-800"><h2 class="text-base font-medium text-gray-800 dark:text-white/90">Valori per componente</h2><p class="mt-1 text-sm text-gray-500 dark:text-gray-400">Equivalente testuale del grafico.</p></div><div class="overflow-x-auto"><table class="min-w-full"><thead class="border-b border-gray-100 dark:border-gray-800"><tr><th class="px-5 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400">Componente</th><th class="px-5 py-3 text-right text-xs font-medium text-gray-500 dark:text-gray-400">Valore</th></tr></thead><tbody class="divide-y divide-gray-100 dark:divide-gray-800">@foreach($breakdown as $row)<tr><td class="px-5 py-3 text-sm text-gray-500 dark:text-gray-400">{{ $row['label'] }}</td><td class="px-5 py-3 text-right text-sm font-semibold text-gray-800 dark:text-white/90">{{ $row['value'] }}</td></tr>@endforeach</tbody></table></div></article>
            </section>
        @else
            <div class="mt-6 rounded-2xl border border-dashed border-gray-300 bg-white px-6 py-14 text-center dark:border-gray-700 dark:bg-white/[0.03]"><h2 class="text-base font-medium text-gray-800 dark:text-white/90">Nessun dato economico corrente</h2><p class="mt-2 text-sm text-gray-500 dark:text-gray-400">Nessuna riga di spesa corrente e non eliminata corrisponde ai filtri selezionati.</p></div>
        @endif
    @endif
@endsection
