@extends('layouts.app')
@section('content')
<x-common.page-breadcrumb pageTitle="Anni di pianificazione" />
@if(session('success'))<div class="mb-6 rounded-lg border border-success-200 bg-success-50 px-4 py-3 text-sm text-success-700">{{ session('success') }}</div>@endif
<div class="grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px]">
 <section class="overflow-hidden rounded-2xl border border-gray-200 bg-white dark:border-gray-800 dark:bg-white/[.03]" x-data="{ open:false, action:'', version:0, label:'', title:'' }"><div class="border-b border-gray-100 px-6 py-5 dark:border-gray-800"><h1 class="font-semibold text-gray-800 dark:text-white">Anni disponibili</h1></div><div class="overflow-x-auto"><table class="min-w-full"><thead><tr class="border-b border-gray-100 text-left text-xs text-gray-500 dark:border-gray-800"><th class="px-6 py-3">Anno</th><th class="px-6 py-3">Intervallo</th><th class="px-6 py-3">Stato</th><th class="px-6 py-3 text-right">Azioni</th></tr></thead><tbody class="divide-y divide-gray-100 dark:divide-gray-800">@forelse($planningYears as $year)<tr><td class="px-6 py-4 font-medium text-gray-800 dark:text-white">{{ $year['label'] }}</td><td class="px-6 py-4 text-sm text-gray-500">{{ $year['startsAt'] }} — {{ $year['endsAt'] }}</td><td class="px-6 py-4"><x-ui.badge :color="$year['isActive'] ? 'success' : 'gray'">{{ $year['isActive'] ? 'Attivo' : 'Inattivo' }}</x-ui.badge></td><td class="px-6 py-4 text-right">@if($year['isActive'] && $abilities['deactivate'])<button class="text-sm font-medium text-warning-600" @click="open=true;action='{{ route('operational.planning-years.deactivate',$year['id']) }}';version={{ $year['lockVersion'] }};label='{{ $year['label'] }}';title='Disattiva anno'">Disattiva</button>@elseif(!$year['isActive'] && $abilities['reactivate'])<button class="text-sm font-medium text-success-600" @click="open=true;action='{{ route('operational.planning-years.reactivate',$year['id']) }}';version={{ $year['lockVersion'] }};label='{{ $year['label'] }}';title='Riattiva anno'">Riattiva</button>@endif</td></tr>@empty<tr><td colspan="4" class="px-6 py-10 text-center text-sm text-gray-500">Nessun anno configurato.</td></tr>@endforelse</tbody></table></div><div x-show="open" x-cloak class="fixed inset-0 z-99999 flex items-center justify-center bg-gray-900/50 p-4" @keydown.escape.window="open=false"><div @click.outside="open=false" class="w-full max-w-md rounded-2xl bg-white p-6 dark:bg-gray-900"><h2 x-text="title" class="text-lg font-semibold text-gray-800 dark:text-white"></h2><p class="mt-2 text-sm text-gray-500">Confermi l'operazione per l'anno <span x-text="label"></span>?</p><form method="POST" :action="action" class="mt-6 flex justify-end gap-3">@csrf<input name="lock_version" :value="version" type="hidden"><x-ui.button type="button" variant="secondary" @click="open=false">Annulla</x-ui.button><x-ui.button type="submit">Conferma</x-ui.button></form></div></div></section>
 @if($abilities['create'])<aside class="h-fit rounded-2xl border border-gray-200 bg-white p-6 dark:border-gray-800 dark:bg-white/[.03]"><h2 class="font-semibold text-gray-800 dark:text-white">Nuovo anno</h2><form method="POST" action="{{ route('operational.planning-years.store') }}" class="mt-5">@csrf<label class="mb-1.5 block text-sm font-medium text-gray-700 dark:text-gray-300" for="year_label">Anno</label><input class="h-11 w-full rounded-lg border border-gray-300 bg-transparent px-4 text-sm dark:border-gray-700" id="year_label" name="year_label" inputmode="numeric" value="{{ old('year_label') }}" required>@error('year_label')<p class="mt-1 text-xs text-error-500">{{ $message }}</p>@enderror<div class="mt-5"><x-ui.button type="submit">Crea anno</x-ui.button></div></form></aside>@endif
</div>
@endsection
