import { Link } from "react-router";
import type { ContractOccurrence, GeneratedExpense } from "../../api/contracts";
import { ArrowRightIcon, CloseLineIcon, PlusIcon, TrashBinIcon } from "../../icons";
import { routes } from "../../navigation/routes";
import { formatDate, formatMoney } from "../../presentation/formatters";
import { domainLabel } from "../../presentation/labels";
import IconButton from "../common/IconButton";
import Badge from "../ui/badge/Badge";
import Button from "../ui/button/Button";
import { Table, TableBody, TableCell, TableHeader, TableRow } from "../ui/table";

export default function ContractOccurrenceTable({ occurrences, generatedExpenses, canGenerate, canSuppress, canResume, canDeleteGenerated, busyKey, onSynchronize, onSuppress, onResume, onResumeAndGenerate, onDeleteGenerated }: { occurrences: ContractOccurrence[]; generatedExpenses: GeneratedExpense[]; canGenerate: boolean; canSuppress: boolean; canResume: boolean; canDeleteGenerated: boolean; busyKey: string | null; onSynchronize: () => void; onSuppress: (occurrence: ContractOccurrence) => void; onResume: (occurrence: ContractOccurrence) => void; onResumeAndGenerate: (occurrence: ContractOccurrence) => void; onDeleteGenerated: (expense: GeneratedExpense) => void }) {
  return <div className="space-y-6">
    <section><div className="mb-3 flex items-center justify-between gap-3"><h3 className="text-lg font-semibold text-gray-800 dark:text-white/90">Ricorrenze</h3>{canGenerate ? <Button size="sm" variant="outline" onClick={onSynchronize} disabled={busyKey !== null}>Sincronizza</Button> : null}</div>
      {occurrences.length === 0 ? <p className="rounded-xl border border-dashed border-gray-300 p-5 text-sm text-gray-500 dark:border-gray-700 dark:text-gray-400">Nessuna ricorrenza prevista.</p> : <div className="max-w-full overflow-x-auto"><Table><TableHeader className="border-y border-gray-100 dark:border-gray-800"><TableRow>{['Anno', 'Data', 'Lordo', 'Stato', 'Azioni'].map((heading) => <TableCell key={heading} isHeader className="whitespace-nowrap py-3 text-start text-theme-xs font-medium text-gray-500 dark:text-gray-400">{heading}</TableCell>)}</TableRow></TableHeader><TableBody className="divide-y divide-gray-100 dark:divide-gray-800">{occurrences.map((occurrence) => { const key=`occurrence:${occurrence.source_key}`; const busy=busyKey===key; const state=occurrence.suppressed ? 'suppressed' : occurrence.expense_id ? 'generated' : occurrence.generation_state ?? 'pending'; return <TableRow key={occurrence.source_key}><TableCell className="py-3 text-sm font-medium text-gray-800 dark:text-white/90">{occurrence.planning_year}</TableCell><TableCell className="py-3 text-sm text-gray-600 dark:text-gray-300">{formatDate(occurrence.occurrence_date)}</TableCell><TableCell className="whitespace-nowrap py-3 text-sm text-gray-800 dark:text-white/90">{formatMoney(occurrence.gross, occurrence.currency ?? 'EUR')}</TableCell><TableCell className="py-3"><Badge color={occurrence.suppressed ? 'warning' : occurrence.expense_id ? 'success' : 'info'} size="sm">{domainLabel(state)}</Badge></TableCell><TableCell className="py-3"><div className="flex items-center gap-2">{canSuppress && !occurrence.suppressed ? <IconButton icon={CloseLineIcon} label="Sopprimi ricorrenza" onClick={() => onSuppress(occurrence)} disabled={busy} /> : null}{canResume && occurrence.suppressed ? <IconButton icon={ArrowRightIcon} label="Riprendi ricorrenza" onClick={() => onResume(occurrence)} disabled={busy} /> : null}{canResume && occurrence.suppressed ? <IconButton icon={PlusIcon} label="Riprendi e genera la ricorrenza" onClick={() => onResumeAndGenerate(occurrence)} disabled={busy} /> : null}</div></TableCell></TableRow>; })}</TableBody></Table></div>}
    </section>
    <section><h3 className="mb-3 text-lg font-semibold text-gray-800 dark:text-white/90">Spese Generate</h3>{generatedExpenses.length === 0 ? <p className="rounded-xl border border-dashed border-gray-300 p-5 text-sm text-gray-500 dark:border-gray-700 dark:text-gray-400">Nessuna spesa generata.</p> : <div className="max-w-full overflow-x-auto"><Table><TableHeader className="border-y border-gray-100 dark:border-gray-800"><TableRow>{['Titolo', 'Data', 'Lordo', 'Stato', 'Azioni'].map((heading) => <TableCell key={heading} isHeader className="whitespace-nowrap py-3 text-start text-theme-xs font-medium text-gray-500 dark:text-gray-400">{heading}</TableCell>)}</TableRow></TableHeader><TableBody className="divide-y divide-gray-100 dark:divide-gray-800">{generatedExpenses.map((expense) => <TableRow key={expense.id}><TableCell className="py-3"><Link to={routes.spesa(expense.id)} className="text-sm font-medium text-gray-800 hover:text-brand-500 dark:text-white/90">{expense.title}</Link></TableCell><TableCell className="py-3 text-sm text-gray-600 dark:text-gray-300">{formatDate(expense.occurrence_date)}</TableCell><TableCell className="whitespace-nowrap py-3 text-sm text-gray-800 dark:text-white/90">{formatMoney(expense.gross, expense.currency ?? 'EUR')}</TableCell><TableCell className="py-3"><Badge color={expense.confirmation_state === 'confirmed' ? 'success' : 'warning'} size="sm">{domainLabel(expense.confirmation_state)}</Badge></TableCell><TableCell className="py-3">{canDeleteGenerated ? <IconButton icon={TrashBinIcon} label={`Elimina ${expense.title}`} onClick={() => onDeleteGenerated(expense)} disabled={busyKey !== null} destructive /> : null}</TableCell></TableRow>)}</TableBody></Table></div>}</section>
  </div>;
}
