import { useCallback, useEffect, useState } from "react";
import { ApiError } from "../../api/client";
import { createPlanningYear, deactivatePlanningYear, listPlanningYears, reactivatePlanningYear, type PlanningYear } from "../../api/planningYears";
import { CheckCircleIcon, CloseLineIcon } from "../../icons";
import { formatDate } from "../../presentation/formatters";
import ComponentCard from "../common/ComponentCard";
import IconButton from "../common/IconButton";
import PageBreadcrumb from "../common/PageBreadCrumb";
import InputField from "../form/input/InputField";
import Label from "../form/Label";
import Alert from "../ui/alert/Alert";
import Badge from "../ui/badge/Badge";
import Button from "../ui/button/Button";
import { Modal } from "../ui/modal";
import { Table, TableBody, TableCell, TableHeader, TableRow } from "../ui/table";

export default function PlanningYearsView({ canView, canCreate, canDeactivate, canReactivate }: { canView: boolean; canCreate: boolean; canDeactivate: boolean; canReactivate: boolean }) {
  const [years,setYears]=useState<PlanningYear[]>([]); const [value,setValue]=useState(""); const [open,setOpen]=useState(false); const [error,setError]=useState<string|null>(null); const [loading,setLoading]=useState(false); const [busy,setBusy]=useState(false);
  const load=useCallback(async()=>{if(!canView)return;setLoading(true);try{setYears((await listPlanningYears()).data);}catch(requestError){setError(ApiError.from(requestError).message);}finally{setLoading(false);}},[canView]); useEffect(()=>{void load();},[load]);
  const submit=async(event:React.FormEvent)=>{event.preventDefault();const year=Number.parseInt(value,10);if(!/^\d{4}$/.test(value)){setError("Inserisci un anno di quattro cifre.");return;}setBusy(true);try{const item=await createPlanningYear(year);setYears(items=>[...items,item].sort((a,b)=>a.year_label-b.year_label));setValue("");setOpen(false);}catch(requestError){setError(ApiError.from(requestError).message);}finally{setBusy(false);}};
  const change=async(year:PlanningYear,active:boolean)=>{setBusy(true);try{const item=active?await reactivatePlanningYear(year.id,year.lock_version):await deactivatePlanningYear(year.id,year.lock_version);setYears(items=>items.map(row=>row.id===item.id?item:row));}catch(requestError){setError(ApiError.from(requestError).message);}finally{setBusy(false);}};
  return <><PageBreadcrumb pageTitle="Anni di Pianificazione" subtitle="Periodi annuali disponibili nel Tenant corrente." actions={canCreate?<Button size="sm" onClick={()=>setOpen(true)}>Nuovo Anno di Pianificazione</Button>:null}/>{error?<Alert variant="error" title="Operazione non riuscita" message={error}/>:null}<ComponentCard title="Registro Anni di Pianificazione">{loading?<Alert variant="info" title="Caricamento degli anni" message="Recupero del registro in corso."/>:years.length===0?<Alert variant="info" title="Nessun anno di pianificazione" message="Non sono presenti anni nel Tenant corrente."/>:<div className="max-w-full overflow-x-auto"><Table><TableHeader className="border-y border-gray-100 dark:border-gray-800"><TableRow>{["Anno","Periodo","Stato","Azioni"].map(head=><TableCell key={head} isHeader className="py-3 text-start text-theme-xs font-medium text-gray-500 dark:text-gray-400">{head}</TableCell>)}</TableRow></TableHeader><TableBody className="divide-y divide-gray-100 dark:divide-gray-800">{years.map(year=><TableRow key={year.id}><TableCell className="py-3 font-medium text-gray-800 dark:text-white/90">{year.year_label}</TableCell><TableCell className="py-3 text-sm text-gray-600 dark:text-gray-300">{formatDate(year.start_date)} – {formatDate(year.end_date)}</TableCell><TableCell className="py-3"><Badge color={year.active?"success":"light"}>{year.active?"Attivo":"Inattivo"}</Badge></TableCell><TableCell className="py-3">{year.active&&canDeactivate?<IconButton icon={CloseLineIcon} label={`Disattiva l'anno ${year.year_label}`} onClick={()=>void change(year,false)} disabled={busy}/>:!year.active&&canReactivate?<IconButton icon={CheckCircleIcon} label={`Riattiva l'anno ${year.year_label}`} onClick={()=>void change(year,true)} disabled={busy}/>:null}</TableCell></TableRow>)}</TableBody></Table></div>}</ComponentCard><Modal isOpen={open} onClose={()=>setOpen(false)} className="max-w-lg p-6"><h2 className="pr-12 text-lg font-semibold text-gray-800 dark:text-white/90">Nuovo Anno di Pianificazione</h2><form onSubmit={submit} className="mt-5"><Label htmlFor="planning-year-label">Anno</Label><InputField id="planning-year-label" type="number" min="1000" max="9999" value={value} onChange={event=>setValue(event.target.value)} /><div className="mt-6 flex justify-end gap-3"><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Annulla</Button><Button disabled={busy}>{busy?"Creazione…":"Crea Anno"}</Button></div></form></Modal></>;
}
