import { useCallback, useEffect, useState } from "react";
import { ApiError } from "../../api/client"; import { createPlanningYear, deactivatePlanningYear, listPlanningYears, reactivatePlanningYear, type PlanningYear } from "../../api/planningYears"; import ComponentCard from "../common/ComponentCard"; import InputField from "../form/input/InputField"; import Label from "../form/Label"; import Badge from "../ui/badge/Badge"; import Button from "../ui/button/Button"; import { Table, TableBody, TableCell, TableHeader, TableRow } from "../ui/table";
export default function PlanningYearsView({ canView, canCreate, canDeactivate, canReactivate }: { canView: boolean; canCreate: boolean; canDeactivate: boolean; canReactivate: boolean }) {
  const [years, setYears] = useState<PlanningYear[]>([]); const [value, setValue] = useState(""); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { if (!canView) return; try { setYears((await listPlanningYears()).data); } catch (e) { setError(ApiError.from(e).message); } }, [canView]);
  useEffect(() => { void load(); }, [load]);
  const submit = async (e: React.FormEvent) => { e.preventDefault(); if (!canCreate) return; try { const item = await createPlanningYear(Number(value)); setYears((items) => [...items, item].sort((a, b) => a.year_label - b.year_label)); setValue(""); } catch (err) { setError(ApiError.from(err).message); } };
  const change = async (year: PlanningYear, active: boolean) => { if (!(active ? canReactivate : canDeactivate)) return; try { const item = active ? await reactivatePlanningYear(year.id, year.lock_version) : await deactivatePlanningYear(year.id, year.lock_version); setYears((items) => items.map((row) => row.id === item.id ? item : row)); } catch (e) { setError(ApiError.from(e).message); } };
  return <div className="space-y-6">{canCreate && <ComponentCard title="New planning year"><form onSubmit={submit} className="flex flex-wrap items-end gap-4"><div className="w-48"><Label htmlFor="planning-year-label">Year</Label><InputField id="planning-year-label" type="number" min="1000" max="9999" value={value} onChange={(e) => setValue(e.target.value)} /></div><Button type="submit">Create year</Button></form></ComponentCard>}{error && <p className="text-sm text-error-500">{error}</p>}<ComponentCard title="Planning years" desc="Fixed-calendar planning years for the selected tenant."><div className="max-w-full overflow-x-auto"><Table><TableHeader><TableRow>{["Year", "Period", "Status", "Actions"].map((head) => <TableCell key={head} isHeader className="py-3 text-start text-xs font-medium text-gray-500">{head}</TableCell>)}</TableRow></TableHeader><TableBody className="divide-y divide-gray-100 dark:divide-gray-800">{years.map((year) => <TableRow key={year.id}><TableCell className="py-3 font-medium">{year.year_label}</TableCell><TableCell className="py-3 text-sm text-gray-500">{year.start_date} — {year.end_date}</TableCell><TableCell className="py-3"><Badge color={year.active ? "success" : "light"}>{year.active ? "Active" : "Inactive"}</Badge></TableCell><TableCell className="py-3">{year.active && canDeactivate && <Button type="button" size="sm" variant="outline" onClick={() => void change(year, false)}>Deactivate</Button>}{!year.active && canReactivate && <Button type="button" size="sm" variant="outline" onClick={() => void change(year, true)}>Reactivate</Button>}</TableCell></TableRow>)}</TableBody></Table></div></ComponentCard></div>;
}
