@extends('layouts.app')
@section('title',$contract['title'])
@section('content')
<div class="mb-6 flex flex-wrap items-start justify-between gap-4"><div><a href="{{ route('operational.contracts.index') }}" class="text-sm text-brand-500">Contratti</a><h1 class="mt-1 text-2xl font-semibold text-gray-800 dark:text-white">{{ $contract['title'] }}</h1><p class="mt-1 text-sm text-gray-500">Termini, spese generate e controlli delle occorrenze.</p></div><div class="flex gap-2">@if($abilities['update'])<a href="{{ route('operational.contracts.edit',$contract['id']) }}" class="rounded-lg border border-gray-300 bg-white px-4 py-3 text-sm dark:border-gray-700 dark:bg-gray-900">Modifica</a>@endif @if($abilities['delete'])<button x-data @click="$dispatch('open-delete-contract')" class="rounded-lg bg-error-500 px-4 py-3 text-sm text-white">Elimina contratto</button>@endif</div></div>
<div class="grid gap-5 lg:grid-cols-3"><section class="rounded-2xl border border-gray-200 bg-white p-5 lg:col-span-2 dark:border-gray-800 dark:bg-white/[0.03]"><span class="rounded-full px-2.5 py-1 text-xs {{ $contract['active']?'bg-success-50 text-success-600':'bg-gray-100 text-gray-600' }}">{{ $contract['active']?'Attivo':'Inattivo' }}</span><dl class="mt-5 grid gap-5 sm:grid-cols-2">
@foreach(['Fornitore'=>'vendorName','Centro di costo'=>'costCenterName','Periodo'=>'effectiveStart','Data rinnovo'=>'renewalDate','Preavviso rinnovo'=>'renewalNoticeDays','Descrizione'=>'description','Note rinnovo'=>'renewalNotes'] as $label=>$field)
    @if($contract[$field] !== null)
        <div class="{{ in_array($field,['description','renewalNotes'])?'sm:col-span-2':'' }}"><dt class="text-xs uppercase text-gray-500">{{ $label }}</dt><dd class="mt-1 whitespace-pre-wrap text-sm text-gray-800 dark:text-white">
            @if($field==='effectiveStart')
                {{ $contract['effectiveStart'] }} – {{ $contract['effectiveEnd'] }}
            @elseif($field==='renewalNoticeDays')
                {{ $contract[$field] }} giorni
            @else
                {{ $contract[$field] }}
            @endif
        </dd></div>
    @endif
@endforeach
</dl></section>
<section class="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-white/[0.03]"><h2 class="font-semibold">Controlli generazione</h2><div class="mt-4 grid gap-3">@if($abilities['synchronize'])<form method="POST" action="{{ route('operational.contracts.synchronize',$contract['id']) }}">@csrf<button class="w-full rounded-lg bg-brand-500 px-4 py-3 text-sm text-white">Sincronizza</button></form>@endif @if($abilities['generate'])<form method="POST" x-data action="{{ route('operational.contracts.generate',[$contract['id'],'YEAR']) }}" @submit.prevent="if($refs.year.value) $el.action=$el.action.replace('YEAR',$refs.year.value); else return; $el.submit()"><input x-ref="year" type="hidden" value="{{ $planningYears[0]['value'] ?? '' }}"><label class="label">Anno pianificazione</label><select x-model="$refs.year.value" class="field"><option value="">Seleziona</option>@foreach($planningYears as $year)<option value="{{ $year['value'] }}">{{ $year['label'] }}</option>@endforeach</select><button class="mt-3 w-full rounded-lg border border-gray-300 px-4 py-3 text-sm dark:border-gray-700">Genera anno selezionato</button></form>@endif @if(!$abilities['synchronize'] && !$abilities['generate'])<p class="text-sm text-gray-500">Non hai accesso alle azioni di generazione.</p>@endif</div></section></div>
<section class="mt-6"><h2 class="mb-3 text-lg font-semibold">Termini</h2><div class="grid gap-4 lg:grid-cols-2">@forelse($contract['terms'] as $term)<article class="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-white/[0.03]"><div class="flex justify-between gap-4"><div><div class="flex gap-2"><span class="rounded-full bg-brand-50 px-2.5 py-1 text-xs text-brand-500">{{ $term['billingCycle'] }}</span>@if($term['autoRenew'])<span class="rounded-full bg-success-50 px-2.5 py-1 text-xs text-success-600">Rinnovo automatico</span>@endif</div><h3 class="mt-3 font-medium">{{ $term['effectiveStart'] }} – {{ $term['effectiveEnd'] }}</h3></div>@if($abilities['deleteTerm'])<button x-data @click="$dispatch('open-delete-term',{id:{{ $term['id'] }},version:{{ $term['lockVersion'] }}})" class="text-sm text-error-500">Elimina</button>@endif</div><dl class="mt-5 grid grid-cols-3 gap-3 border-t border-gray-100 pt-4 text-sm dark:border-gray-800">@foreach(['Netto'=>'net','IVA'=>'vat','Lordo'=>'gross'] as $label=>$field)<div><dt class="text-xs text-gray-500">{{ $label }}</dt><dd class="mt-1 font-medium">{{ $term[$field] }}</dd></div>@endforeach</dl></article>@empty<div class="rounded-2xl border border-dashed border-gray-300 p-8 text-center text-sm text-gray-500">Nessun termine corrente.</div>@endforelse</div></section>
<section class="mt-6"><h2 class="mb-3 text-lg font-semibold">Spese generate</h2>@if(count($generatedExpenses))<div class="overflow-x-auto rounded-2xl border border-gray-200 bg-white dark:border-gray-800 dark:bg-white/[0.03]"><table class="min-w-full text-left text-sm"><thead class="border-b border-gray-100 text-xs uppercase text-gray-500 dark:border-gray-800"><tr><th class="px-5 py-4">Occorrenza</th><th class="px-5 py-4">Spesa</th><th class="px-5 py-4">Conferma</th><th class="px-5 py-4">Gestione</th><th class="px-5 py-4">Lordo</th></tr></thead><tbody class="divide-y divide-gray-100 dark:divide-gray-800">@foreach($generatedExpenses as $generated)<tr><td class="px-5 py-4">{{ $generated['periodLabel'] ?? $generated['occurrenceDate'] ?? '—' }}</td><td class="px-5 py-4"><a class="text-brand-500" href="{{ $generated['href'] }}">{{ $generated['title'] }}</a></td><td class="px-5 py-4">{{ $generated['confirmationState']==='confirmed'?'Confermato':'Da confermare' }}</td><td class="px-5 py-4">{{ $generated['isSystemManaged']?'Gestita da contratto':'Autorevole utente' }}</td><td class="px-5 py-4">{{ $generated['gross'] }}</td></tr>@endforeach</tbody></table></div>@else<div class="rounded-2xl border border-dashed border-gray-300 p-8 text-center text-sm text-gray-500">Sincronizza o genera un anno valido per materializzare le occorrenze.</div>@endif</section>
<section class="mt-6 grid gap-5 xl:grid-cols-2"><div><h2 class="mb-3 text-lg font-semibold">Occorrenze soppresse</h2><div class="grid gap-3">@forelse($suppressedOccurrences as $occurrence)<article class="rounded-2xl border border-gray-200 bg-white p-4 dark:border-gray-800 dark:bg-white/[0.03]"><p class="font-medium">{{ $occurrence['occurrenceDate'] ?? 'Data non disponibile' }}</p>@if($abilities['resume'])<div class="mt-3 flex gap-2"><form method="POST" action="{{ route('operational.contracts.occurrences.resume',[$contract['id'],$occurrence['sourceKey']]) }}">@csrf<button class="text-sm text-brand-500">Riprendi</button></form><form method="POST" action="{{ route('operational.contracts.occurrences.resume-and-generate',[$contract['id'],$occurrence['sourceKey']]) }}">@csrf<button class="text-sm text-brand-500">Riprendi e genera</button></form></div>@endif</article>@empty<div class="rounded-2xl border border-dashed border-gray-300 p-6 text-center text-sm text-gray-500">Nessuna occorrenza soppressa.</div>@endforelse</div></div><div><h2 class="mb-3 text-lg font-semibold">Attività revisioni</h2><div class="rounded-2xl border border-gray-200 bg-white divide-y divide-gray-100 dark:border-gray-800 dark:divide-gray-800 dark:bg-white/[0.03]">@forelse($revisionActivity as $activity)<div class="p-4"><div class="flex justify-between gap-3"><p class="font-medium">{{ $activity['operation'] }}</p><time class="text-xs text-gray-500">{{ $activity['timestamp'] }}</time></div><p class="mt-1 text-sm text-gray-500">{{ $activity['actor'] ?? 'Sistema' }}@if($activity['summary']) · {{ $activity['summary'] }}@endif</p></div>@empty<div class="p-6 text-center text-sm text-gray-500">Nessun riepilogo disponibile.</div>@endforelse</div></div></section>
@if($abilities['delete'])<div x-data="contractDeletion({{ $deletionReasonRequired?'true':'false' }})" @open-delete-contract.window="openContract=true" @open-delete-term.window="term=$event.detail;openTerm=true"><template x-teleport="body"><div x-cloak x-show="openContract||openTerm" class="fixed inset-0 z-50 flex items-center justify-center p-5"><div @click="openContract=false;openTerm=false" class="absolute inset-0 bg-gray-900/50"></div><form method="POST" :action="openTerm ? '{{ route('operational.contracts.terms.destroy',[$contract['id'],'TERM']) }}'.replace('TERM',term.id) : '{{ route('operational.contracts.destroy',$contract['id']) }}'" class="relative w-full max-w-lg rounded-2xl bg-white p-6 dark:bg-gray-900">@csrf<input type="hidden" name="_method" value="DELETE"><input type="hidden" name="lock_version" :value="openTerm?term.version:{{ $contract['lockVersion'] }}"><h2 class="text-lg font-semibold" x-text="openTerm?'Elimina termine':'Elimina contratto'"></h2><p class="mt-2 text-sm text-gray-500" x-text="openTerm?'L’eliminazione ferma la generazione futura. Le spese generate restano preservate.':'L’eliminazione è terminale. Le spese generate restano e diventano autorevoli per l’utente.'"></p><div class="mt-4"><label class="label">Motivazione @if($deletionReasonRequired)(obbligatoria)@endif</label><textarea name="deletion_reason" x-model="reason" rows="3" class="textarea"></textarea></div><div class="mt-6 flex justify-end gap-3"><button type="button" @click="openContract=false;openTerm=false" class="px-4 py-2 text-sm">Annulla</button><button :disabled="required&&!reason.trim()" class="rounded-lg bg-error-500 px-4 py-2 text-sm text-white disabled:opacity-40">Elimina</button></div></form></div></template></div>@endif
@if(!$abilities['delete'] && $abilities['deleteTerm'])<div x-data="{open:false,term:{id:null,version:null},reason:'',required:{{ $deletionReasonRequired?'true':'false' }}}" @open-delete-term.window="term=$event.detail;open=true"><template x-teleport="body"><div x-cloak x-show="open" class="fixed inset-0 z-50 flex items-center justify-center p-5"><div @click="open=false" class="absolute inset-0 bg-gray-900/50"></div><form method="POST" :action="'{{ route('operational.contracts.terms.destroy',[$contract['id'],'TERM']) }}'.replace('TERM',term.id)" class="relative w-full max-w-lg rounded-2xl bg-white p-6 dark:bg-gray-900">@csrf @method('DELETE')<input type="hidden" name="lock_version" :value="term.version"><h2 class="text-lg font-semibold">Elimina termine</h2><p class="mt-2 text-sm text-gray-500">L’eliminazione ferma la generazione futura. Le spese generate restano preservate.</p><div class="mt-4"><label class="label">Motivazione @if($deletionReasonRequired)(obbligatoria)@endif</label><textarea name="deletion_reason" x-model="reason" rows="3" class="textarea"></textarea></div><div class="mt-6 flex justify-end gap-3"><button type="button" @click="open=false" class="px-4 py-2 text-sm">Annulla</button><button :disabled="required&&!reason.trim()" class="rounded-lg bg-error-500 px-4 py-2 text-sm text-white disabled:opacity-40">Elimina</button></div></form></div></template></div>@endif
<style>.field{height:2.75rem;width:100%;border-radius:.5rem;border:1px solid #d1d5db;background:transparent;padding:0 .75rem;font-size:.875rem}.textarea{width:100%;border-radius:.5rem;border:1px solid #d1d5db;background:transparent;padding:.5rem .75rem;font-size:.875rem}.label{margin-bottom:.375rem;display:block;font-size:.875rem;font-weight:500}</style><script>function contractDeletion(required){return{required,reason:'',openContract:false,openTerm:false,term:{id:null,version:null}}}</script>
@endsection
