import { useCallback, useEffect, useState } from "react";
import { ApiError } from "../../api/client";
import { assignUserRoles, createUser, deactivateUser, listUserRoleOptions, listUsers, resetUserPassword, updateUser, type TenantUser } from "../../api/users";
import { roleLabel } from "../../presentation/labels";
import ComponentCard from "../common/ComponentCard";import PageBreadcrumb from "../common/PageBreadCrumb";import Label from "../form/Label";import Checkbox from "../form/input/Checkbox";import InputField from "../form/input/InputField";import Alert from "../ui/alert/Alert";import Badge from "../ui/badge/Badge";import Button from "../ui/button/Button";import {Modal} from "../ui/modal";

export default function UsersView({canView,canManage}:{canView:boolean;canManage:boolean}){
 const[users,setUsers]=useState<TenantUser[]>([]),[roles,setRoles]=useState<Array<{id:number;name:string}>>([]);const[search,setSearch]=useState(""),[applied,setApplied]=useState("");const[selected,setSelected]=useState<TenantUser|null>(null);const[form,setForm]=useState({name:"",email:"",password:"",roles:[] as number[]});const[open,setOpen]=useState(false),[resetTarget,setResetTarget]=useState<TenantUser|null>(null);const[resetPassword,setResetPassword]=useState("");const[loading,setLoading]=useState(false),[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{if(!canView)return;setLoading(true);setError(null);try{const result=await listUsers({q:applied||undefined,per_page:100});setUsers(result.data);setRoles(canManage?(await listUserRoleOptions()).data:[]);}catch(e){setError(ApiError.from(e).message);}finally{setLoading(false);}},[applied,canManage,canView]);useEffect(()=>{void load()},[load]);
 const begin=(user:TenantUser|null)=>{if(!canManage)return;setSelected(user);setForm({name:user?.name??"",email:user?.email??"",password:"",roles:user?.role_ids??[]});setOpen(true)};
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(!canManage||form.roles.length===0)return;setBusy(true);try{let saved=selected?await updateUser(selected.id,{name:form.name,email:form.email}):await createUser(form);if(selected)saved=await assignUserRoles(saved.id,form.roles);setUsers(current=>selected?current.map(item=>item.id===saved.id?saved:item):[saved,...current]);setOpen(false);}catch(err){setError(ApiError.from(err).message);}finally{setBusy(false)}};
 const deactivate=async(user:TenantUser)=>{setBusy(true);try{const saved=await deactivateUser(user.id);setUsers(current=>current.map(item=>item.id===saved.id?saved:item));}catch(e){setError(ApiError.from(e).message)}finally{setBusy(false)}};
 const reset=async()=>{if(!resetTarget||!resetPassword)return;setBusy(true);try{await resetUserPassword(resetTarget.id,resetPassword,resetPassword);setResetTarget(null);setResetPassword("");}catch(e){setError(ApiError.from(e).message)}finally{setBusy(false)}};
 return <><PageBreadcrumb pageTitle="Utenti" subtitle="Utenti e ruoli del Tenant corrente." actions={canManage?<Button size="sm" onClick={()=>begin(null)}>Nuovo Utente</Button>:null}/>{error?<Alert variant="error" title="Operazione non riuscita" message={error}/>:null}<ComponentCard title="Registro Utenti"><form onSubmit={e=>{e.preventDefault();setApplied(search.trim())}} className="mb-5 flex flex-col gap-3 sm:flex-row"><InputField type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nome o email"/><Button>Applica ricerca</Button></form>{loading?<Alert variant="info" title="Caricamento degli utenti" message="Recupero del registro in corso."/>:users.length===0?<Alert variant="info" title="Nessun utente" message="Nessun utente corrisponde alla ricerca corrente."/>:<div className="space-y-3">{users.map(user=><article key={user.id} className="flex flex-col justify-between gap-3 rounded-xl border border-gray-200 p-4 sm:flex-row dark:border-gray-800"><div><p className="font-medium text-gray-800 dark:text-white">{user.name}</p><p className="text-sm text-gray-500">{user.email}</p><div className="mt-2 flex flex-wrap gap-1">{user.roles?.map(role=><Badge key={role.id} color="info" size="sm">{roleLabel(role.name)}</Badge>)}</div></div><div className="flex items-center gap-2"><Badge color={user.active?"success":"light"}>{user.active?"Attivo":"Inattivo"}</Badge>{canManage?<><Button size="sm" variant="outline" onClick={()=>begin(user)}>Modifica</Button>{user.active?<Button size="sm" variant="outline" onClick={()=>void deactivate(user)}>Disattiva</Button>:null}<Button size="sm" variant="outline" onClick={()=>setResetTarget(user)}>Password</Button></>:null}</div></article>)}</div>}</ComponentCard>
 <Modal isOpen={open} onClose={()=>setOpen(false)} className="max-w-2xl p-6"><h2 className="text-lg font-semibold">{selected?"Modifica Utente":"Nuovo Utente"}</h2><form onSubmit={save} className="mt-5 space-y-4"><div><Label>Nome</Label><InputField value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div><Label>Email</Label><InputField type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div>{!selected?<div><Label>Password</Label><InputField type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></div>:null}<fieldset><legend>Ruoli</legend>{roles.map(role=><Checkbox key={role.id} label={roleLabel(role.name)} checked={form.roles.includes(role.id)} onChange={checked=>setForm({...form,roles:checked?[...form.roles,role.id]:form.roles.filter(id=>id!==role.id)})}/>)}</fieldset><div className="flex justify-end gap-3"><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Annulla</Button><Button disabled={busy}>Salva</Button></div></form></Modal>
 <Modal isOpen={resetTarget!==null} onClose={()=>setResetTarget(null)} className="max-w-lg p-6"><h2 className="text-lg font-semibold">Reimposta password</h2><div className="mt-4"><InputField type="password" value={resetPassword} onChange={e=>setResetPassword(e.target.value)}/></div><div className="mt-4 flex justify-end gap-3"><Button variant="outline" onClick={()=>setResetTarget(null)}>Annulla</Button><Button onClick={()=>void reset()} disabled={busy||!resetPassword}>Reimposta</Button></div></Modal></>;
}
